/** Cardio: locomoção e saltos. Os "sem impacto" são úteis para treinos joint-friendly. */
import type { SeedExercise } from '../types';

export const CARDIO_EXERCISES: SeedExercise[] = [
  {
    slug: 'march-in-place',
    name: 'March in Place',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['CARDIOVASCULAR', 'HIP_FLEXORS'],
    secondaryMuscles: ['QUADS', 'CALVES', 'CORE'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 4,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Marcha no lugar',
        description: 'Marcha no sítio levantando bem os joelhos e mexendo os braços. Sem impacto: serve para aquecer ou para cardio suave.',
        cues: ['Joelhos à altura da anca', 'Braços em movimento como a andar depressa', 'Aumenta o ritmo aos poucos'],
      },
      'en-US': {
        name: 'March in place',
        description: 'March on the spot lifting the knees high and swinging the arms. No impact: good for warming up or gentle cardio.',
        cues: ['Knees to hip height', 'Arms moving like brisk walking', 'Increase the pace gradually'],
      },
    },
    easier: [],
    harder: ['high-knees'],
  },
  {
    slug: 'step-jacks',
    name: 'Step Jacks',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['CARDIOVASCULAR'],
    secondaryMuscles: ['SHOULDERS', 'CALVES', 'ABDUCTORS'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 5,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Polichinelos sem salto',
        description: 'A versão sem impacto do polichinelo: dá um passo para o lado enquanto os braços sobem, volta e repete para o outro lado.',
        cues: ['Passo largo para o lado', 'Braços sobem acima da cabeça', 'Alterna os lados com ritmo'],
      },
      'en-US': {
        name: 'Step jacks',
        description: 'The low-impact jumping jack: step to the side as the arms rise, return and repeat to the other side.',
        cues: ['Big step to the side', 'Arms rise overhead', 'Alternate sides with rhythm'],
      },
    },
    easier: [],
    harder: ['jumping-jacks'],
  },
  {
    slug: 'jumping-jacks',
    name: 'Jumping Jacks',
    category: 'CARDIO',
    movementPattern: 'JUMP',
    primaryMuscles: ['CARDIOVASCULAR'],
    secondaryMuscles: ['CALVES', 'SHOULDERS', 'ABDUCTORS'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Polichinelos',
        description: 'Salta abrindo as pernas e levantando os braços acima da cabeça, volta a fechar. O aquecimento clássico.',
        cues: ['Aterra suave na ponta dos pés', 'Braços esticados acima da cabeça', 'Respira com o ritmo'],
      },
      'en-US': {
        name: 'Jumping jacks',
        description: 'Jump the legs apart while raising the arms overhead, then jump back together. The classic warm-up.',
        cues: ['Land softly on the balls of the feet', 'Arms straight overhead', 'Breathe with the rhythm'],
      },
    },
    easier: [],
  },
  {
    slug: 'star-jumps',
    name: 'Star Jumps',
    category: 'PLYOMETRIC',
    movementPattern: 'JUMP',
    primaryMuscles: ['CARDIOVASCULAR', 'QUADS'],
    secondaryMuscles: ['GLUTES', 'CALVES', 'SHOULDERS'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Saltos em estrela',
        description: 'De um meio agachamento, salta explosivamente abrindo braços e pernas em estrela e aterra de novo em agachamento.',
        cues: ['Começa em meio agachamento', 'Abre tudo no ar', 'Aterra suave e vai logo para o próximo'],
      },
      'en-US': {
        name: 'Star jumps',
        description: 'From a half squat, jump explosively spreading arms and legs into a star and land back in the squat.',
        cues: ['Start in a half squat', 'Open everything in the air', 'Land softly and go straight into the next'],
      },
    },
    easier: ['jumping-jacks'],
  },
  {
    slug: 'high-knees',
    name: 'High Knees',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['CARDIOVASCULAR', 'HIP_FLEXORS'],
    secondaryMuscles: ['QUADS', 'CALVES', 'CORE'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Joelhos ao peito',
        description: 'Corrida no lugar levando os joelhos à altura da anca o mais rápido possível. Cardio intenso e core.',
        cues: ['Joelhos à altura da anca', 'Tronco direito, não te inclines para trás', 'Braços a acompanhar a corrida'],
      },
      'en-US': {
        name: 'High knees',
        description: 'Run on the spot driving the knees to hip height as fast as possible. Intense cardio and core.',
        cues: ['Knees to hip height', 'Torso tall, do not lean back', 'Arms pumping with the run'],
      },
    },
    easier: [],
  },
  {
    slug: 'butt-kicks',
    name: 'Butt Kicks',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['CARDIOVASCULAR', 'HAMSTRINGS'],
    secondaryMuscles: ['CALVES', 'QUADS'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Calcanhares ao glúteo',
        description: 'Corrida no lugar levando os calcanhares ao rabo. Aquece os isquiotibiais e sobe o ritmo cardíaco.',
        cues: ['Calcanhar toca no glúteo', 'Joelhos apontam para baixo', 'Leve na ponta dos pés'],
      },
      'en-US': {
        name: 'Butt kicks',
        description: 'Run on the spot bringing the heels up to the glutes. Warms up the hamstrings and raises the heart rate.',
        cues: ['Heel touches the glute', 'Knees point down', 'Light on the balls of the feet'],
      },
    },
    easier: ['march-in-place'],
  },
  {
    slug: 'running-in-place',
    name: 'Running in Place',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['CARDIOVASCULAR'],
    secondaryMuscles: ['QUADS', 'CALVES', 'HAMSTRINGS'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Corrida no lugar',
        description: 'Corrida no sítio a um ritmo que consigas manter. Ajusta a intensidade com a velocidade e a altura dos joelhos.',
        cues: ['Aterra suave na parte da frente do pé', 'Tronco ligeiramente inclinado à frente', 'Braços a 90 graus a acompanhar'],
      },
      'en-US': {
        name: 'Running in place',
        description: 'Run on the spot at a pace you can sustain. Adjust intensity with speed and knee height.',
        cues: ['Land softly on the forefoot', 'Torso slightly forward', 'Arms at 90 degrees, pumping'],
      },
    },
    easier: ['march-in-place'],
  },
  {
    slug: 'fast-feet',
    name: 'Fast Feet',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['CARDIOVASCULAR', 'CALVES'],
    secondaryMuscles: ['QUADS', 'HIP_FLEXORS'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Pés rápidos',
        description: 'Em posição atlética com os pés afastados, corre no lugar com passos minúsculos e o mais rápidos possível.',
        cues: ['Joelhos ligeiramente dobrados, anca baixa', 'Passos pequenos, pés mal saem do chão', 'Máxima velocidade'],
      },
      'en-US': {
        name: 'Fast feet',
        description: 'In an athletic stance with feet apart, run on the spot with tiny steps as fast as possible.',
        cues: ['Knees slightly bent, hips low', 'Tiny steps, feet barely leave the floor', 'Maximum speed'],
      },
    },
    easier: ['march-in-place'],
  },
  {
    slug: 'shadow-boxing',
    name: 'Shadow Boxing',
    category: 'CARDIO',
    movementPattern: 'ROTATION',
    primaryMuscles: ['CARDIOVASCULAR', 'SHOULDERS'],
    secondaryMuscles: ['CORE', 'OBLIQUES', 'TRICEPS'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 5.5,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Shadow boxing',
        description: 'Socos no ar com deslocação: diretos, ganchos e uppercuts, rodando o tronco em cada golpe. Cardio sem impacto que trabalha o core.',
        cues: ['Roda a anca com cada soco', 'Mãos voltam sempre à cara', 'Mexe os pés, não fiques parado'],
      },
      'en-US': {
        name: 'Shadow boxing',
        description: 'Punching the air while moving: jabs, hooks and uppercuts, rotating the torso with every strike. No-impact cardio that works the core.',
        cues: ['Rotate the hips with each punch', 'Hands always return to the face', 'Keep the feet moving'],
      },
    },
    easier: [],
  },
  {
    slug: 'half-burpee',
    name: 'Half Burpee',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['CARDIOVASCULAR', 'QUADS'],
    secondaryMuscles: ['CORE', 'SHOULDERS', 'GLUTES'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Meio burpee',
        description: 'Mãos no chão, pés saltam (ou andam) para trás até à prancha e voltam à frente; levanta sem saltar. O burpee sem impacto.',
        cues: ['Mãos por baixo dos ombros', 'Prancha firme antes de voltar', 'Podes andar com os pés em vez de saltar'],
      },
      'en-US': {
        name: 'Half burpee',
        description: 'Hands on the floor, feet jump (or step) back to a plank and back forward; stand up without jumping. The no-impact burpee.',
        cues: ['Hands under the shoulders', 'Solid plank before returning', 'You can step the feet instead of jumping'],
      },
    },
    easier: [],
  },
  {
    slug: 'burpee',
    name: 'Burpee',
    category: 'CARDIO',
    movementPattern: 'JUMP',
    primaryMuscles: ['CARDIOVASCULAR', 'FULL_BODY'],
    secondaryMuscles: ['QUADS', 'CORE', 'SHOULDERS', 'GLUTES'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Burpees',
        description: 'Agacha, mãos no chão, pés para trás em prancha, pés à frente e salta com os braços acima da cabeça. Corpo inteiro em cada repetição.',
        cues: ['Prancha firme, anca não cai', 'Salta e estica tudo no topo', 'Aterra suave e vai logo para o chão'],
      },
      'en-US': {
        name: 'Burpee',
        description: 'Squat, hands down, feet back to a plank, feet forward and jump with arms overhead. Whole body in every rep.',
        cues: ['Solid plank, hips do not sag', 'Jump and extend fully at the top', 'Land softly and drop straight back down'],
      },
    },
    easier: ['half-burpee'],
  },
  {
    slug: 'burpee-push-up',
    name: 'Burpee with Push-Up',
    category: 'CARDIO',
    movementPattern: 'JUMP',
    primaryMuscles: ['CARDIOVASCULAR', 'FULL_BODY'],
    secondaryMuscles: ['CHEST', 'TRICEPS', 'QUADS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 4,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Burpees com flexão',
        description: 'O burpee completo: com uma flexão no chão antes de voltar a saltar. O exercício mais exigente do catálogo de cardio.',
        cues: ['Peito ao chão na flexão', 'Não deixes a anca subir primeiro', 'Ritmo que consigas manter'],
      },
      'en-US': {
        name: 'Burpee with push-up',
        description: 'The full burpee: with a push-up on the floor before jumping back up. The most demanding exercise in the cardio catalog.',
        cues: ['Chest to the floor on the push-up', 'Do not let the hips rise first', 'A pace you can sustain'],
      },
    },
    easier: ['burpee'],
  },
  {
    slug: 'skater-jumps',
    name: 'Skater Jumps',
    category: 'PLYOMETRIC',
    movementPattern: 'JUMP',
    primaryMuscles: ['GLUTES', 'QUADS'],
    secondaryMuscles: ['ABDUCTORS', 'CALVES', 'CARDIOVASCULAR', 'CORE'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Saltos de patinador',
        description: 'Salta lateralmente de uma perna para a outra, aterrando numa perna e cruzando a outra atrás. Conta o total de saltos.',
        cues: ['Aterra numa perna e estabiliza', 'Joelho alinhado com o pé ao aterrar', 'Braços ajudam no balanço'],
      },
      'en-US': {
        name: 'Skater jumps',
        description: 'Jump sideways from one leg to the other, landing on one leg and sweeping the other behind. Count total jumps.',
        cues: ['Land on one leg and stabilize', 'Knee aligned with the foot on landing', 'Arms assist the swing'],
      },
    },
    easier: ['lateral-lunge'],
  },
  {
    slug: 'tuck-jumps',
    name: 'Tuck Jumps',
    category: 'PLYOMETRIC',
    movementPattern: 'JUMP',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['CALVES', 'HIP_FLEXORS', 'CORE', 'CARDIOVASCULAR'],
    equipment: ['NONE'],
    difficulty: 4,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Saltos com joelhos ao peito',
        description: 'Salta o mais alto possível puxando os joelhos ao peito. Muito explosivo; poucas repetições e boa aterragem.',
        cues: ['Joelhos ao peito, não o peito aos joelhos', 'Aterra suave e absorve com as pernas', 'Pausa entre saltos se precisares'],
      },
      'en-US': {
        name: 'Tuck jumps',
        description: 'Jump as high as possible pulling the knees to the chest. Very explosive; low reps and clean landings.',
        cues: ['Knees to chest, not chest to knees', 'Land softly and absorb with the legs', 'Pause between jumps if needed'],
      },
    },
    easier: ['jump-squat'],
  },
  {
    slug: 'plank-jacks',
    name: 'Plank Jacks',
    category: 'CARDIO',
    movementPattern: 'JUMP',
    primaryMuscles: ['CORE', 'CARDIOVASCULAR'],
    secondaryMuscles: ['SHOULDERS', 'ABDUCTORS', 'CALVES'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Prancha com polichinelo',
        description: 'Em prancha alta, salta abrindo e fechando as pernas como num polichinelo. Core e cardio.',
        cues: ['Ombros por cima das mãos', 'Anca fixa, não sobe nem balança', 'Aterra suave'],
      },
      'en-US': {
        name: 'Plank jacks',
        description: 'In a high plank, jump the legs apart and together like a jumping jack. Core and cardio.',
        cues: ['Shoulders over the hands', 'Hips fixed, no piking or swaying', 'Land softly'],
      },
    },
    easier: ['mountain-climbers'],
  },
  {
    slug: 'jump-rope',
    name: 'Jump Rope',
    category: 'CARDIO',
    movementPattern: 'JUMP',
    primaryMuscles: ['CARDIOVASCULAR', 'CALVES'],
    secondaryMuscles: ['SHOULDERS', 'FOREARMS', 'QUADS'],
    equipment: ['JUMP_ROPE'],
    difficulty: 2,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 11,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Saltar à corda',
        description: 'Saltos baixos e rápidos na ponta dos pés, rodando a corda com os pulsos. Cardio muito eficiente em pouco espaço.',
        cues: ['Salta baixo, só o suficiente', 'Roda com os pulsos, cotovelos junto ao corpo', 'Olhar em frente'],
      },
      'en-US': {
        name: 'Jump rope',
        description: 'Low, quick jumps on the balls of the feet, turning the rope with the wrists. Very efficient cardio in little space.',
        cues: ['Jump low, just enough', 'Turn with the wrists, elbows in', 'Eyes forward'],
      },
    },
    easier: ['jumping-jacks'],
  },
  {
    slug: 'box-jump',
    name: 'Box Jump',
    category: 'PLYOMETRIC',
    movementPattern: 'JUMP',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['CALVES', 'HAMSTRINGS', 'CORE'],
    equipment: ['PLYO_BOX'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Salto à caixa',
        description: 'Salta para cima de uma caixa estável e aterra em agachamento suave. Desce sempre a andar, não a saltar.',
        cues: ['Balança os braços e explode', 'Aterra com o pé inteiro em cima', 'Desce a andar para poupar os joelhos'],
      },
      'en-US': {
        name: 'Box jump',
        description: 'Jump onto a stable box and land in a soft squat. Always step down, do not jump down.',
        cues: ['Swing the arms and explode', 'Land with the whole foot on top', 'Step down to spare the knees'],
      },
    },
    easier: ['jump-squat'],
  },
];
