/**
 * Core.
 *
 * Nota sobre movementPattern: o enum não tem "flexão do tronco". Os exercícios
 * de anti-extensão / flexão (elevações de pernas, hollow, v-ups, flutter kicks)
 * ficam em ISOMETRIC porque o trabalho do abdómen é sobretudo manter a pélvis
 * e a lombar fixas; os rotacionais em ROTATION; os de estabilidade com membros
 * em movimento (dead bug, bird dog, shoulder taps, pallof) em ANTI_ROTATION.
 */
import type { SeedExercise } from '../types';

export const CORE_EXERCISES: SeedExercise[] = [
  {
    slug: 'dead-bug',
    name: 'Dead Bug',
    category: 'CORE',
    movementPattern: 'ANTI_ROTATION',
    primaryMuscles: ['CORE'],
    secondaryMuscles: ['HIP_FLEXORS', 'OBLIQUES'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 2.8,
    defaultTempo: '2-0-2-0',
    translations: {
      'pt-PT': {
        name: 'Dead bug',
        description: 'De costas, braços para o teto e joelhos a 90 graus; estica o braço e a perna opostos sem deixar a lombar levantar do chão. Estabilidade lombo-pélvica pura.',
        cues: ['Lombar colada ao chão o tempo todo', 'Braço e perna opostos, devagar', 'Expira ao esticar'],
      },
      'en-US': {
        name: 'Dead bug',
        description: 'On your back, arms to the ceiling and knees at 90 degrees; extend the opposite arm and leg without letting the lower back lift. Pure lumbopelvic stability.',
        cues: ['Lower back pressed into the floor throughout', 'Opposite arm and leg, slowly', 'Exhale as you extend'],
      },
    },
    easier: [],
  },
  {
    slug: 'bird-dog',
    name: 'Bird Dog',
    category: 'CORE',
    movementPattern: 'ANTI_ROTATION',
    primaryMuscles: ['CORE', 'LOWER_BACK'],
    secondaryMuscles: ['GLUTES', 'SHOULDERS'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 2.8,
    defaultTempo: '2-1-2-0',
    translations: {
      'pt-PT': {
        name: 'Bird dog',
        description: 'De quatro, estica o braço e a perna opostos até ficarem em linha com o tronco, sem rodar a anca. Excelente para a lombar.',
        cues: ['Anca e ombros nivelados', 'Estica até ficar em linha, não mais alto', 'Segura 1 segundo e volta devagar'],
      },
      'en-US': {
        name: 'Bird dog',
        description: 'On all fours, extend the opposite arm and leg until level with the torso, without rotating the hips. Excellent for the lower back.',
        cues: ['Hips and shoulders level', 'Extend to a line, not higher', 'Hold 1 second and return slowly'],
      },
    },
    easier: [],
  },
  {
    slug: 'plank',
    name: 'Plank',
    category: 'CORE',
    movementPattern: 'ISOMETRIC',
    primaryMuscles: ['CORE'],
    secondaryMuscles: ['SHOULDERS', 'GLUTES', 'QUADS'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 3.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Prancha',
        description: 'Antebraços no chão, corpo em linha reta dos calcanhares à cabeça. Aguenta a posição com tudo apertado.',
        cues: ['Glúteos e abdómen apertados', 'Não deixes a anca cair nem subir', 'Olhar para o chão, pescoço neutro'],
      },
      'en-US': {
        name: 'Plank',
        description: 'Forearms on the floor, body in a straight line from heels to head. Hold the position with everything tight.',
        cues: ['Squeeze glutes and abs', 'Hips neither sag nor pike', 'Look at the floor, neutral neck'],
      },
    },
    easier: ['bird-dog'],
  },
  {
    slug: 'plank-shoulder-taps',
    name: 'Plank Shoulder Taps',
    category: 'CORE',
    movementPattern: 'ANTI_ROTATION',
    primaryMuscles: ['CORE', 'OBLIQUES'],
    secondaryMuscles: ['SHOULDERS', 'TRICEPS'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Prancha com toques no ombro',
        description: 'Em prancha alta (braços esticados), toca com uma mão no ombro oposto sem deixar a anca balançar. Conta o total de toques.',
        cues: ['Pés mais afastados para estabilizar', 'A anca não roda', 'Toca devagar, sem pressa'],
      },
      'en-US': {
        name: 'Plank shoulder taps',
        description: 'In a high plank (straight arms), tap the opposite shoulder with one hand without letting the hips sway. Count total taps.',
        cues: ['Wider feet for stability', 'Hips do not rotate', 'Tap slowly, no rush'],
      },
    },
    easier: ['plank'],
  },
  {
    slug: 'plank-leg-lift',
    name: 'Plank Leg Lift',
    category: 'CORE',
    movementPattern: 'ANTI_ROTATION',
    primaryMuscles: ['CORE', 'GLUTES'],
    secondaryMuscles: ['SHOULDERS', 'LOWER_BACK'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: '1-1-1-0',
    translations: {
      'pt-PT': {
        name: 'Prancha com elevação de perna',
        description: 'Em prancha, levanta uma perna esticada alguns centímetros, segura e troca. Conta o total de elevações.',
        cues: ['Levanta só até à altura da anca', 'Anca nivelada, não abre para o lado', 'Aperta o glúteo da perna que sobe'],
      },
      'en-US': {
        name: 'Plank leg lift',
        description: 'In a plank, lift one straight leg a few centimeters, hold and switch. Count total lifts.',
        cues: ['Lift only to hip height', 'Hips level, do not open to the side', 'Squeeze the glute of the lifting leg'],
      },
    },
    easier: ['plank'],
  },
  {
    slug: 'side-plank',
    name: 'Side Plank',
    category: 'CORE',
    movementPattern: 'ISOMETRIC',
    primaryMuscles: ['OBLIQUES', 'CORE'],
    secondaryMuscles: ['SHOULDERS', 'ABDUCTORS'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'DURATION',
    isUnilateral: true,
    metValue: 3.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Prancha lateral',
        description: 'Apoio no antebraço e no bordo do pé, corpo em linha de lado. Fortalece os oblíquos e o glúteo médio. Apoia o joelho de baixo para facilitar.',
        cues: ['Cotovelo por baixo do ombro', 'Anca alta, corpo em linha', 'Olhar em frente, não para baixo'],
      },
      'en-US': {
        name: 'Side plank',
        description: 'Supported on the forearm and the edge of the foot, body in a line on its side. Strengthens the obliques and glute medius. Drop the bottom knee to make it easier.',
        cues: ['Elbow under the shoulder', 'Hips high, body in a line', 'Look forward, not down'],
      },
    },
    easier: ['plank'],
  },
  {
    slug: 'side-plank-hip-dip',
    name: 'Side Plank Hip Dip',
    category: 'CORE',
    movementPattern: 'ROTATION',
    primaryMuscles: ['OBLIQUES', 'CORE'],
    secondaryMuscles: ['SHOULDERS', 'ABDUCTORS'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 3.8,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Prancha lateral com descida da anca',
        description: 'Em prancha lateral, baixa a anca até quase tocar no chão e sobe de novo. Trabalho dinâmico dos oblíquos.',
        cues: ['Só a anca se mexe', 'Sobe mais alto do que a linha do corpo', 'Ombro sempre por cima do cotovelo'],
      },
      'en-US': {
        name: 'Side plank hip dip',
        description: 'In a side plank, lower the hip until it almost touches the floor and lift it back up. Dynamic oblique work.',
        cues: ['Only the hips move', 'Lift higher than the body line', 'Shoulder always over the elbow'],
      },
    },
    easier: ['side-plank'],
  },
  {
    slug: 'hollow-hold',
    name: 'Hollow Hold',
    category: 'CORE',
    movementPattern: 'ISOMETRIC',
    primaryMuscles: ['CORE'],
    secondaryMuscles: ['HIP_FLEXORS', 'QUADS'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 3.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Hollow hold',
        description: 'De costas, lombar colada ao chão, braços e pernas esticados e levantados, ombros fora do chão. A posição base da ginástica.',
        cues: ['Lombar não descola do chão', 'Braços junto às orelhas', 'Se perderes a lombar, dobra os joelhos'],
      },
      'en-US': {
        name: 'Hollow hold',
        description: 'On your back, lower back pressed down, arms and legs straight and raised, shoulders off the floor. The base gymnastics position.',
        cues: ['Lower back never leaves the floor', 'Arms by the ears', 'If the lower back lifts, bend the knees'],
      },
    },
    easier: ['dead-bug'],
  },
  {
    slug: 'hollow-rocks',
    name: 'Hollow Rocks',
    category: 'CORE',
    movementPattern: 'ISOMETRIC',
    primaryMuscles: ['CORE'],
    secondaryMuscles: ['HIP_FLEXORS', 'QUADS'],
    equipment: ['NONE'],
    difficulty: 4,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Hollow rocks',
        description: 'Na posição de hollow, balança para a frente e para trás como uma cadeira de baloiço, sem perder a forma.',
        cues: ['A forma não muda ao balançar', 'Movimento pequeno e ritmado', 'Lombar sempre em contacto no ponto baixo'],
      },
      'en-US': {
        name: 'Hollow rocks',
        description: 'From the hollow position, rock back and forth like a rocking chair without losing the shape.',
        cues: ['Shape does not change while rocking', 'Small, rhythmic movement', 'Lower back stays in contact at the low point'],
      },
    },
    easier: ['hollow-hold'],
  },
  {
    slug: 'leg-raises',
    name: 'Lying Leg Raises',
    category: 'CORE',
    movementPattern: 'ISOMETRIC',
    primaryMuscles: ['CORE', 'HIP_FLEXORS'],
    secondaryMuscles: ['QUADS'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.3,
    defaultTempo: '3-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Elevação de pernas',
        description: 'Deitado de costas, levanta as pernas esticadas até à vertical e desce devagar sem tocar no chão. Mãos debaixo do rabo para ajudar.',
        cues: ['Lombar colada ao chão', 'Desce devagar, é aí que trabalha', 'Não toques no chão entre repetições'],
      },
      'en-US': {
        name: 'Lying leg raises',
        description: 'Lying on your back, raise straight legs to vertical and lower slowly without touching the floor. Hands under the hips to help.',
        cues: ['Lower back pressed down', 'Lower slowly, that is where it works', 'Do not touch the floor between reps'],
      },
    },
    easier: ['dead-bug'],
  },
  {
    slug: 'flutter-kicks',
    name: 'Flutter Kicks',
    category: 'CORE',
    movementPattern: 'ISOMETRIC',
    primaryMuscles: ['CORE', 'HIP_FLEXORS'],
    secondaryMuscles: ['QUADS'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Flutter kicks',
        description: 'De costas, pernas esticadas ligeiramente levantadas, alterna pequenos pontapés para cima e para baixo. Quanto mais baixas as pernas, mais difícil.',
        cues: ['Lombar não descola do chão', 'Pontapés curtos e rápidos', 'Sobe as pernas se a lombar levantar'],
      },
      'en-US': {
        name: 'Flutter kicks',
        description: 'On your back, straight legs slightly raised, alternate small kicks up and down. The lower the legs, the harder.',
        cues: ['Lower back stays on the floor', 'Short, quick kicks', 'Raise the legs if the lower back lifts'],
      },
    },
    easier: ['leg-raises'],
  },
  {
    slug: 'v-ups',
    name: 'V-Ups',
    category: 'CORE',
    movementPattern: 'ISOMETRIC',
    primaryMuscles: ['CORE', 'HIP_FLEXORS'],
    secondaryMuscles: ['QUADS'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'V-ups',
        description: 'Deitado e esticado, levanta ao mesmo tempo tronco e pernas até as mãos tocarem nos pés, formando um V. Desce com controlo.',
        cues: ['Braços e pernas sobem ao mesmo tempo', 'Pernas esticadas', 'Desce devagar sem bater no chão'],
      },
      'en-US': {
        name: 'V-ups',
        description: 'Lying flat, lift torso and legs together until the hands touch the feet, forming a V. Lower with control.',
        cues: ['Arms and legs rise together', 'Legs straight', 'Lower slowly without slamming down'],
      },
    },
    easier: ['leg-raises'],
  },
  {
    slug: 'crunch',
    name: 'Crunch',
    category: 'CORE',
    movementPattern: 'ISOMETRIC',
    primaryMuscles: ['CORE'],
    secondaryMuscles: [],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 2.8,
    defaultTempo: '2-1-1-0',
    translations: {
      'pt-PT': {
        name: 'Abdominal',
        description: 'De costas com os joelhos dobrados, enrola o tronco até as omoplatas saírem do chão. Movimento curto; o queixo não vai ao peito.',
        cues: ['Enrola o tronco, não puxes o pescoço', 'Pausa de 1 segundo no topo', 'Expira ao subir'],
      },
      'en-US': {
        name: 'Crunch',
        description: 'On your back with knees bent, curl the torso until the shoulder blades leave the floor. Short movement; the chin does not go to the chest.',
        cues: ['Curl the torso, do not pull the neck', 'Pause 1 second at the top', 'Exhale on the way up'],
      },
    },
    easier: [],
    harder: ['leg-raises'],
  },
  {
    slug: 'bicycle-crunch',
    name: 'Bicycle Crunch',
    category: 'CORE',
    movementPattern: 'ROTATION',
    primaryMuscles: ['OBLIQUES', 'CORE'],
    secondaryMuscles: ['HIP_FLEXORS'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Abdominal bicicleta',
        description: 'De costas, mãos junto às orelhas, leva o cotovelo ao joelho oposto enquanto a outra perna estica. Conta o total de toques.',
        cues: ['Roda o tronco, não só o cotovelo', 'Perna esticada fica baixa sem tocar no chão', 'Devagar e controlado'],
      },
      'en-US': {
        name: 'Bicycle crunch',
        description: 'On your back, hands by the ears, bring the elbow to the opposite knee while the other leg extends. Count total touches.',
        cues: ['Rotate the torso, not just the elbow', 'Extended leg stays low without touching', 'Slow and controlled'],
      },
    },
    easier: ['crunch'],
  },
  {
    slug: 'russian-twist',
    name: 'Russian Twist',
    category: 'CORE',
    movementPattern: 'ROTATION',
    primaryMuscles: ['OBLIQUES', 'CORE'],
    secondaryMuscles: ['HIP_FLEXORS'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Russian twist',
        description: 'Sentado com o tronco inclinado para trás e os pés levantados (ou no chão), roda o tronco de um lado para o outro. Conta o total de toques.',
        cues: ['Costas direitas, inclinadas para trás', 'Roda os ombros, não só os braços', 'Pés no chão para facilitar'],
      },
      'en-US': {
        name: 'Russian twist',
        description: 'Seated with the torso leaning back and feet lifted (or on the floor), rotate the torso side to side. Count total touches.',
        cues: ['Flat back, leaning back', 'Rotate the shoulders, not just the arms', 'Feet on the floor to make it easier'],
      },
    },
    easier: ['crunch'],
  },
  {
    slug: 'band-pallof-press',
    name: 'Band Pallof Press',
    category: 'CORE',
    movementPattern: 'ANTI_ROTATION',
    primaryMuscles: ['CORE', 'OBLIQUES'],
    secondaryMuscles: ['SHOULDERS', 'GLUTES'],
    equipment: ['RESISTANCE_BAND'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 2.8,
    defaultTempo: '2-2-2-0',
    translations: {
      'pt-PT': {
        name: 'Pallof press com banda',
        description: 'Banda presa ao lado, ao nível do peito; estica os braços à frente e resiste à rotação. Anti-rotação pura, muito amiga da lombar.',
        cues: ['Pés à largura dos ombros, joelhos soltos', 'Aguenta 2 segundos com os braços esticados', 'A anca não roda'],
      },
      'en-US': {
        name: 'Band Pallof press',
        description: 'Band anchored to the side at chest height; press the arms out and resist the rotation. Pure anti-rotation, very back-friendly.',
        cues: ['Feet shoulder-width, soft knees', 'Hold 2 seconds with arms extended', 'Hips do not rotate'],
      },
    },
    easier: ['dead-bug'],
  },
  {
    slug: 'mountain-climbers',
    name: 'Mountain Climbers',
    category: 'CARDIO',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['CORE', 'HIP_FLEXORS'],
    secondaryMuscles: ['SHOULDERS', 'QUADS', 'CARDIOVASCULAR'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Mountain climbers',
        description: 'Em prancha alta, leva os joelhos ao peito alternadamente, em corrida. Core e cardio ao mesmo tempo. Faz devagar para ser só core.',
        cues: ['Ombros por cima das mãos', 'Anca baixa, não sobe', 'Ritmo constante que consigas manter'],
      },
      'en-US': {
        name: 'Mountain climbers',
        description: 'In a high plank, drive the knees to the chest alternately, as if running. Core and cardio at once. Go slow to make it core only.',
        cues: ['Shoulders over the hands', 'Hips low, do not pike', 'Steady pace you can maintain'],
      },
    },
    easier: ['plank-shoulder-taps'],
  },
  {
    slug: 'bear-crawl',
    name: 'Bear Crawl',
    category: 'CORE',
    movementPattern: 'CARRY',
    primaryMuscles: ['CORE', 'SHOULDERS'],
    secondaryMuscles: ['QUADS', 'HIP_FLEXORS', 'TRICEPS'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 6,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Bear crawl',
        description: 'De quatro com os joelhos a dois dedos do chão, avança movendo a mão e o pé opostos. Ida e volta no espaço que tiveres.',
        cues: ['Joelhos sempre perto do chão', 'Costas planas, anca não sobe', 'Passos pequenos e silenciosos'],
      },
      'en-US': {
        name: 'Bear crawl',
        description: 'On all fours with knees hovering just off the floor, move forward with the opposite hand and foot. Go back and forth in the space you have.',
        cues: ['Knees always close to the floor', 'Flat back, hips do not rise', 'Small, quiet steps'],
      },
    },
    easier: ['bird-dog'],
  },
];
