/** Ginásio — nomes em português herdados do protótipo (index.html). */
import type { SeedExercise } from '../types';

export const GYM_EXERCISES: SeedExercise[] = [
  {
    slug: 'dumbbell-bench-press',
    name: 'Dumbbell Bench Press',
    category: 'STRENGTH',
    movementPattern: 'PUSH_HORIZONTAL',
    primaryMuscles: ['CHEST', 'TRICEPS'],
    secondaryMuscles: ['SHOULDERS'],
    equipment: ['DUMBBELLS', 'BENCH'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Supino halteres',
        description: 'Deitado no banco, empurra os halteres do peito até esticar os braços. Mais amplitude e trabalho de estabilidade que a barra.',
        cues: ['Omoplatas juntas e para baixo', 'Cotovelos a 45 graus do tronco', 'Halteres descem até ao nível do peito'],
      },
      'en-US': {
        name: 'Dumbbell bench press',
        description: 'Lying on a bench, press the dumbbells from the chest to straight arms. More range and stability work than the barbell.',
        cues: ['Shoulder blades pinched and down', 'Elbows at 45 degrees from the torso', 'Dumbbells lower to chest level'],
      },
    },
    easier: ['push-up'],
  },
  {
    slug: 'incline-dumbbell-bench-press',
    name: 'Incline Dumbbell Bench Press',
    category: 'STRENGTH',
    movementPattern: 'PUSH_HORIZONTAL',
    primaryMuscles: ['CHEST', 'SHOULDERS'],
    secondaryMuscles: ['TRICEPS'],
    equipment: ['DUMBBELLS', 'BENCH'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Supino inclinado halteres',
        description: 'Supino com o banco a 30 graus. Mais ênfase no peito superior e no ombro anterior.',
        cues: ['Banco a cerca de 30 graus', 'Halteres em linha com o peito superior', 'Não arqueies demasiado a lombar'],
      },
      'en-US': {
        name: 'Incline dumbbell bench press',
        description: 'Bench press with the bench at 30 degrees. More emphasis on the upper chest and front delts.',
        cues: ['Bench at about 30 degrees', 'Dumbbells in line with the upper chest', 'Do not over-arch the lower back'],
      },
    },
    easier: ['dumbbell-bench-press'],
  },
  {
    slug: 'machine-chest-press',
    name: 'Machine Chest Press',
    category: 'STRENGTH',
    movementPattern: 'PUSH_HORIZONTAL',
    primaryMuscles: ['CHEST', 'TRICEPS'],
    secondaryMuscles: ['SHOULDERS'],
    equipment: ['MACHINE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Chest press máquina',
        description: 'Press de peito na máquina. Percurso guiado, ideal para aprender o padrão ou para trabalhar perto da falha em segurança.',
        cues: ['Pegas ao nível do meio do peito', 'Costas apoiadas no encosto', 'Controla a volta, não deixes o peso bater'],
      },
      'en-US': {
        name: 'Machine chest press',
        description: 'Chest press on the machine. Guided path, ideal to learn the pattern or to train close to failure safely.',
        cues: ['Handles at mid-chest level', 'Back against the pad', 'Control the return, do not let the weight slam'],
      },
    },
    easier: ['incline-push-up'],
  },
  {
    slug: 'machine-row',
    name: 'Machine Row',
    category: 'STRENGTH',
    movementPattern: 'PULL_HORIZONTAL',
    primaryMuscles: ['UPPER_BACK', 'LATS'],
    secondaryMuscles: ['BICEPS', 'FOREARMS'],
    equipment: ['MACHINE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-0-1-1',
    translations: {
      'pt-PT': {
        name: 'Remada máquina',
        description: 'Remada com o peito apoiado na máquina. Isola as costas sem exigir estabilidade da lombar.',
        cues: ['Peito colado ao apoio', 'Puxa os cotovelos para trás e aperta as omoplatas', 'Solta devagar até esticar os braços'],
      },
      'en-US': {
        name: 'Machine row',
        description: 'Chest-supported row on the machine. Isolates the back without demanding lower-back stability.',
        cues: ['Chest against the pad', 'Drive the elbows back and squeeze the shoulder blades', 'Release slowly to straight arms'],
      },
    },
    easier: ['band-row'],
  },
  {
    slug: 'seated-cable-row',
    name: 'Seated Cable Row',
    category: 'STRENGTH',
    movementPattern: 'PULL_HORIZONTAL',
    primaryMuscles: ['UPPER_BACK', 'LATS'],
    secondaryMuscles: ['BICEPS', 'FOREARMS', 'LOWER_BACK'],
    equipment: ['CABLE_MACHINE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-0-1-1',
    translations: {
      'pt-PT': {
        name: 'Remada cabo sentado',
        description: 'Sentado na polia baixa, puxa a pega até ao abdómen mantendo o tronco quase imóvel.',
        cues: ['Tronco direito, não balances', 'Pega até ao umbigo', 'Estica os braços por completo na volta'],
      },
      'en-US': {
        name: 'Seated cable row',
        description: 'Seated at the low pulley, pull the handle to the abdomen keeping the torso nearly still.',
        cues: ['Torso upright, no swinging', 'Handle to the navel', 'Fully extend the arms on the return'],
      },
    },
    easier: ['band-row'],
  },
  {
    slug: 'lat-pulldown',
    name: 'Lat Pulldown',
    category: 'STRENGTH',
    movementPattern: 'PULL_VERTICAL',
    primaryMuscles: ['LATS', 'BICEPS'],
    secondaryMuscles: ['UPPER_BACK', 'FOREARMS'],
    equipment: ['CABLE_MACHINE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-0-1-1',
    translations: {
      'pt-PT': {
        name: 'Puxada vertical',
        description: 'Sentado na máquina de puxada, traz a barra até ao peito superior com os cotovelos a apontar para baixo. A alternativa às elevações.',
        cues: ['Inclina ligeiramente o tronco para trás', 'Barra ao peito superior, não atrás do pescoço', 'Cotovelos para baixo e para trás'],
      },
      'en-US': {
        name: 'Lat pulldown',
        description: 'Seated at the pulldown machine, bring the bar to the upper chest with elbows pointing down. The alternative to pull-ups.',
        cues: ['Lean the torso back slightly', 'Bar to the upper chest, not behind the neck', 'Elbows down and back'],
      },
    },
    easier: ['prone-lat-pulldown'],
    harder: ['pull-up'],
  },
  {
    slug: 'face-pull',
    name: 'Face Pull',
    category: 'STRENGTH',
    movementPattern: 'PULL_HORIZONTAL',
    primaryMuscles: ['SHOULDERS', 'UPPER_BACK'],
    secondaryMuscles: [],
    equipment: ['CABLE_MACHINE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3,
    defaultTempo: '2-1-1-0',
    translations: {
      'pt-PT': {
        name: 'Face pulls',
        description: 'Corda na polia alta; puxa em direção à cara abrindo os cotovelos para fora. O melhor exercício para o ombro posterior e a postura.',
        cues: ['Cotovelos altos e para fora', 'Puxa até as mãos ficarem junto às orelhas', 'Roda os ombros para fora no fim'],
      },
      'en-US': {
        name: 'Face pull',
        description: 'Rope on the high pulley; pull toward the face with the elbows flaring out. The best exercise for rear delts and posture.',
        cues: ['Elbows high and out', 'Pull until the hands are by the ears', 'Externally rotate the shoulders at the end'],
      },
    },
    easier: ['band-pull-apart'],
  },
  {
    slug: 'dumbbell-shoulder-press',
    name: 'Dumbbell Shoulder Press',
    category: 'STRENGTH',
    movementPattern: 'PUSH_VERTICAL',
    primaryMuscles: ['SHOULDERS', 'TRICEPS'],
    secondaryMuscles: ['UPPER_BACK', 'CORE'],
    equipment: ['DUMBBELLS'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Press ombros halteres',
        description: 'Sentado ou de pé, empurra os halteres dos ombros até acima da cabeça. O press vertical fundamental.',
        cues: ['Halteres começam ao nível das orelhas', 'Core apertado, não arqueies a lombar', 'Termina com os braços esticados por cima da cabeça'],
      },
      'en-US': {
        name: 'Dumbbell shoulder press',
        description: 'Seated or standing, press the dumbbells from the shoulders to overhead. The fundamental vertical press.',
        cues: ['Dumbbells start at ear level', 'Brace the core, do not arch the lower back', 'Finish with arms straight overhead'],
      },
    },
    easier: ['pike-push-up'],
  },
  {
    slug: 'lateral-raise',
    name: 'Dumbbell Lateral Raise',
    category: 'STRENGTH',
    movementPattern: 'PUSH_VERTICAL',
    primaryMuscles: ['SHOULDERS'],
    secondaryMuscles: ['UPPER_BACK'],
    equipment: ['DUMBBELLS'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Elevações laterais',
        description: 'Halteres ao lado do corpo; levanta os braços de lado até à altura dos ombros. Isola o deltoide lateral.',
        cues: ['Cotovelos ligeiramente dobrados', 'Sobe até à altura dos ombros, não mais', 'Desce em 2 segundos'],
      },
      'en-US': {
        name: 'Dumbbell lateral raise',
        description: 'Dumbbells at the sides; raise the arms out to shoulder height. Isolates the side delts.',
        cues: ['Slight bend in the elbows', 'Raise to shoulder height, no higher', 'Lower over 2 seconds'],
      },
    },
    easier: [],
  },
  {
    slug: 'reverse-fly',
    name: 'Dumbbell Reverse Fly',
    category: 'STRENGTH',
    movementPattern: 'PULL_HORIZONTAL',
    primaryMuscles: ['SHOULDERS', 'UPPER_BACK'],
    secondaryMuscles: [],
    equipment: ['DUMBBELLS'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3,
    defaultTempo: '2-1-1-0',
    translations: {
      'pt-PT': {
        name: 'Reverse fly',
        description: 'Tronco inclinado à frente, abre os braços para os lados com halteres leves. Ombro posterior e músculos entre as omoplatas.',
        cues: ['Costas direitas, tronco quase paralelo ao chão', 'Cotovelos ligeiramente dobrados', 'Aperta as omoplatas no topo'],
      },
      'en-US': {
        name: 'Dumbbell reverse fly',
        description: 'Torso hinged forward, open the arms out to the sides with light dumbbells. Rear delts and the muscles between the shoulder blades.',
        cues: ['Flat back, torso nearly parallel to the floor', 'Slight bend in the elbows', 'Squeeze the shoulder blades at the top'],
      },
    },
    easier: ['prone-ytw'],
  },
  {
    slug: 'dumbbell-biceps-curl',
    name: 'Dumbbell Biceps Curl',
    category: 'STRENGTH',
    movementPattern: 'PULL_VERTICAL',
    primaryMuscles: ['BICEPS'],
    secondaryMuscles: ['FOREARMS'],
    equipment: ['DUMBBELLS'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Curl bíceps halteres',
        description: 'De pé, dobra os cotovelos levando os halteres aos ombros, sem balançar o tronco.',
        cues: ['Cotovelos fixos ao lado do corpo', 'Roda a palma para cima ao subir', 'Desce controlado até esticar'],
      },
      'en-US': {
        name: 'Dumbbell biceps curl',
        description: 'Standing, bend the elbows bringing the dumbbells to the shoulders without swinging the torso.',
        cues: ['Elbows pinned to the sides', 'Rotate the palm up as you lift', 'Lower under control to full extension'],
      },
    },
    easier: [],
  },
  {
    slug: 'hammer-curl',
    name: 'Hammer Curl',
    category: 'STRENGTH',
    movementPattern: 'PULL_VERTICAL',
    primaryMuscles: ['BICEPS', 'FOREARMS'],
    secondaryMuscles: [],
    equipment: ['DUMBBELLS'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Curl martelo',
        description: 'Curl com as palmas viradas uma para a outra, como a segurar um martelo. Mais braquial e antebraço.',
        cues: ['Palmas viradas para dentro', 'Cotovelos não avançam', 'Sem balançar o tronco'],
      },
      'en-US': {
        name: 'Hammer curl',
        description: 'Curl with palms facing each other, as if holding a hammer. More brachialis and forearm.',
        cues: ['Palms facing in', 'Elbows do not drift forward', 'No torso swing'],
      },
    },
    easier: [],
  },
  {
    slug: 'cable-rope-triceps-pushdown',
    name: 'Cable Rope Triceps Pushdown',
    category: 'STRENGTH',
    movementPattern: 'PUSH_VERTICAL',
    primaryMuscles: ['TRICEPS'],
    secondaryMuscles: [],
    equipment: ['CABLE_MACHINE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3,
    defaultTempo: '2-0-1-1',
    translations: {
      'pt-PT': {
        name: 'Tríceps corda',
        description: 'Corda na polia alta; estende os cotovelos para baixo abrindo a corda no fim. Isolamento do tríceps.',
        cues: ['Cotovelos colados ao tronco', 'Abre a corda no fim do movimento', 'Sobe só até 90 graus'],
      },
      'en-US': {
        name: 'Cable rope triceps pushdown',
        description: 'Rope on the high pulley; extend the elbows down, spreading the rope at the end. Triceps isolation.',
        cues: ['Elbows pinned to the torso', 'Spread the rope at the end', 'Return only to 90 degrees'],
      },
    },
    easier: ['bench-dip'],
  },
  {
    slug: 'overhead-triceps-extension',
    name: 'Overhead Dumbbell Triceps Extension',
    category: 'STRENGTH',
    movementPattern: 'PUSH_VERTICAL',
    primaryMuscles: ['TRICEPS'],
    secondaryMuscles: ['SHOULDERS', 'CORE'],
    equipment: ['DUMBBELLS'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Extensão de tríceps acima da cabeça',
        description: 'Um haltere seguro com as duas mãos por cima da cabeça; desce atrás da nuca e volta a esticar. Trabalha a cabeça longa do tríceps.',
        cues: ['Cotovelos apontam para o teto', 'Desce até sentir alongar o tríceps', 'Core apertado, não arqueies'],
      },
      'en-US': {
        name: 'Overhead dumbbell triceps extension',
        description: 'One dumbbell held with both hands overhead; lower behind the head and extend back up. Targets the long head of the triceps.',
        cues: ['Elbows point to the ceiling', 'Lower until you feel the triceps stretch', 'Brace the core, do not arch'],
      },
    },
    easier: ['bench-dip'],
  },
  {
    slug: 'hack-squat',
    name: 'Hack Squat',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CALVES'],
    equipment: ['MACHINE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Hack squat',
        description: 'Agachamento na máquina hack, com as costas apoiadas. Muito quadríceps com pouca exigência técnica.',
        cues: ['Pés à largura dos ombros na plataforma', 'Desce fundo com controlo', 'Não bloqueies os joelhos em cima'],
      },
      'en-US': {
        name: 'Hack squat',
        description: 'Squat on the hack machine with the back supported. Lots of quads with little technical demand.',
        cues: ['Feet shoulder-width on the platform', 'Go deep with control', 'Do not lock the knees at the top'],
      },
    },
    easier: ['goblet-squat'],
  },
  {
    slug: 'leg-press',
    name: 'Leg Press',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CALVES'],
    equipment: ['MACHINE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Prensa de pernas',
        description: 'Empurra a plataforma com os pés a partir da posição sentada. Permite carga alta com segurança.',
        cues: ['Lombar sempre colada ao encosto', 'Desce até 90 graus ou mais sem levantar a anca', 'Não bloqueies os joelhos'],
      },
      'en-US': {
        name: 'Leg press',
        description: 'Push the platform with the feet from the seated position. Allows heavy loads safely.',
        cues: ['Lower back always on the pad', 'Lower to 90 degrees or more without lifting the hips', 'Do not lock the knees'],
      },
    },
    easier: ['goblet-squat'],
  },
  {
    slug: 'romanian-deadlift',
    name: 'Barbell Romanian Deadlift',
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['HAMSTRINGS', 'GLUTES'],
    secondaryMuscles: ['LOWER_BACK', 'CORE', 'FOREARMS', 'UPPER_BACK'],
    equipment: ['BARBELL'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 6,
    defaultTempo: '3-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Peso morto romeno',
        description: 'Com a barra nas mãos, empurra a anca para trás deixando a barra deslizar pelas pernas até sentires os isquiotibiais. Sobe apertando os glúteos.',
        cues: ['Barra colada às pernas', 'Anca para trás, joelhos pouco dobrados', 'Costas direitas do início ao fim'],
      },
      'en-US': {
        name: 'Barbell Romanian deadlift',
        description: 'With the bar in hand, push the hips back letting the bar slide down the legs until you feel the hamstrings. Stand by squeezing the glutes.',
        cues: ['Bar stays against the legs', 'Hips back, knees slightly bent', 'Flat back from start to finish'],
      },
    },
    easier: ['bodyweight-good-morning'],
  },
  {
    slug: 'barbell-hip-thrust',
    name: 'Barbell Hip Thrust',
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE'],
    equipment: ['BARBELL', 'BENCH'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 5,
    defaultTempo: '2-1-1-0',
    translations: {
      'pt-PT': {
        name: 'Hip thrust barra',
        description: 'Hip thrust com a barra sobre a anca (usa uma almofada). O exercício mais eficaz para carregar os glúteos com peso.',
        cues: ['Barra na dobra da anca com almofada', 'Queixo para o peito, olhar em frente', 'Aperta os glúteos 1 segundo no topo'],
      },
      'en-US': {
        name: 'Barbell hip thrust',
        description: 'Hip thrust with the bar across the hips (use a pad). The most effective way to load the glutes with weight.',
        cues: ['Bar in the hip crease with a pad', 'Chin tucked, eyes forward', 'Squeeze the glutes 1 second at the top'],
      },
    },
    easier: ['hip-thrust'],
  },
  {
    slug: 'leg-curl',
    name: 'Leg Curl',
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['HAMSTRINGS'],
    secondaryMuscles: ['CALVES', 'GLUTES'],
    equipment: ['MACHINE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-0-1-1',
    translations: {
      'pt-PT': {
        name: 'Leg curl',
        description: 'Na máquina, sentado ou deitado, dobra os joelhos contra a resistência. Isolamento dos isquiotibiais.',
        cues: ['Anca colada ao banco', 'Dobra o máximo e aperta no fim', 'Volta devagar, sem deixar o peso cair'],
      },
      'en-US': {
        name: 'Leg curl',
        description: 'On the machine, seated or lying, bend the knees against the resistance. Hamstring isolation.',
        cues: ['Hips pinned to the pad', 'Curl fully and squeeze at the end', 'Return slowly, do not let the weight drop'],
      },
    },
    easier: ['single-leg-glute-bridge'],
  },
  {
    slug: 'leg-extension',
    name: 'Leg Extension',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['QUADS'],
    secondaryMuscles: [],
    equipment: ['MACHINE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-1-1-0',
    translations: {
      'pt-PT': {
        name: 'Extensão de pernas',
        description: 'Sentado na máquina, estica os joelhos contra a almofada. Isolamento do quadríceps.',
        cues: ['Costas apoiadas, anca fixa', 'Pausa de 1 segundo com as pernas esticadas', 'Desce em 2 segundos'],
      },
      'en-US': {
        name: 'Leg extension',
        description: 'Seated on the machine, extend the knees against the pad. Quad isolation.',
        cues: ['Back supported, hips fixed', 'Pause 1 second with legs straight', 'Lower over 2 seconds'],
      },
    },
    easier: ['wall-sit'],
  },
  {
    slug: 'standing-calf-raise-machine',
    name: 'Standing Calf Raise (Machine)',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['CALVES'],
    secondaryMuscles: [],
    equipment: ['MACHINE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3,
    defaultTempo: '2-1-1-1',
    translations: {
      'pt-PT': {
        name: 'Gémeos em pé (máquina)',
        description: 'Na máquina de gémeos em pé, sobe na ponta dos pés e desce com pausa em baixo. Amplitude completa.',
        cues: ['Pausa em baixo, sente o alongamento', 'Sobe o mais alto possível', 'Joelhos esticados mas não bloqueados'],
      },
      'en-US': {
        name: 'Standing calf raise (machine)',
        description: 'On the standing calf machine, rise onto the toes and lower with a pause at the bottom. Full range of motion.',
        cues: ['Pause at the bottom, feel the stretch', 'Rise as high as possible', 'Knees straight but not locked'],
      },
    },
    easier: ['calf-raise'],
  },
  {
    slug: 'machine-hip-abduction',
    name: 'Machine Hip Abduction',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['ABDUCTORS', 'GLUTES'],
    secondaryMuscles: [],
    equipment: ['MACHINE'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3,
    defaultTempo: '2-1-1-0',
    translations: {
      'pt-PT': {
        name: 'Abdução máquina',
        description: 'Sentado na máquina, abre as pernas contra a resistência. Inclina o tronco à frente para apanhar mais glúteo médio.',
        cues: ['Tronco ligeiramente inclinado à frente', 'Abre o máximo e segura 1 segundo', 'Volta devagar'],
      },
      'en-US': {
        name: 'Machine hip abduction',
        description: 'Seated on the machine, open the legs against the resistance. Lean the torso forward to hit more glute medius.',
        cues: ['Torso slightly forward', 'Open fully and hold 1 second', 'Return slowly'],
      },
    },
    easier: [],
  },
  {
    slug: 'weighted-crunch',
    name: 'Weighted Crunch',
    category: 'CORE',
    movementPattern: 'ISOMETRIC',
    primaryMuscles: ['CORE'],
    secondaryMuscles: [],
    equipment: ['DUMBBELLS'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3,
    defaultTempo: '2-1-1-0',
    translations: {
      'pt-PT': {
        name: 'Abdominal com carga',
        description: 'Abdominal com um haltere ou disco ao peito. Permite progredir o abdómen em séries de 10 a 15 como qualquer outro músculo.',
        cues: ['Carga colada ao peito', 'Enrola o tronco, não puxes o pescoço', 'Pausa de 1 segundo no topo'],
      },
      'en-US': {
        name: 'Weighted crunch',
        description: 'Crunch holding a dumbbell or plate on the chest. Lets you progress the abs in sets of 10 to 15 like any other muscle.',
        cues: ['Load held against the chest', 'Curl the torso, do not pull the neck', 'Pause 1 second at the top'],
      },
    },
    easier: ['crunch'],
  },
];
