/** Dobradiça de anca — pontes, hip thrust, RDL, swing, nordic. */
import type { SeedExercise } from '../types';

export const HINGE_EXERCISES: SeedExercise[] = [
  {
    slug: 'glute-bridge',
    name: 'Glute Bridge',
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE', 'LOWER_BACK'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-1-1-0',
    translations: {
      'pt-PT': {
        name: 'Ponte de glúteos',
        description: 'Deitado de costas com os joelhos dobrados, empurra os calcanhares e levanta a anca até o corpo ficar em linha. O exercício base para os glúteos.',
        cues: ['Calcanhares perto dos glúteos', 'Aperta os glúteos no topo', 'Não arqueies a lombar'],
      },
      'en-US': {
        name: 'Glute bridge',
        description: 'Lying on your back with knees bent, drive through the heels and lift the hips until the body is in a line. The foundation exercise for glutes.',
        cues: ['Heels close to the glutes', 'Squeeze the glutes at the top', 'Do not arch the lower back'],
      },
    },
    easier: [],
  },
  {
    slug: 'single-leg-glute-bridge',
    name: 'Single-Leg Glute Bridge',
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 3.5,
    defaultTempo: '2-1-1-0',
    translations: {
      'pt-PT': {
        name: 'Ponte de glúteos a uma perna',
        description: 'Ponte com uma perna esticada ou dobrada no ar. Duplica a carga no glúteo de apoio e corrige assimetrias.',
        cues: ['Anca nivelada, não deixes rodar', 'Empurra o calcanhar de apoio', 'Segura 1 segundo no topo'],
      },
      'en-US': {
        name: 'Single-leg glute bridge',
        description: 'Bridge with one leg held straight or bent in the air. Doubles the load on the working glute and fixes asymmetries.',
        cues: ['Hips level, do not let them rotate', 'Drive through the working heel', 'Hold 1 second at the top'],
      },
    },
    easier: ['glute-bridge'],
  },
  {
    slug: 'hip-thrust',
    name: 'Hip Thrust',
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE'],
    equipment: ['BENCH'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-1-1-0',
    translations: {
      'pt-PT': {
        name: 'Hip thrust',
        description: 'Ombros apoiados num banco ou sofá, pés no chão; sobe a anca até ficar em linha com os joelhos. Maior amplitude que a ponte.',
        cues: ['Queixo para o peito, olhar em frente', 'Canelas verticais no topo', 'Aperta os glúteos em cima'],
      },
      'en-US': {
        name: 'Hip thrust',
        description: 'Shoulders on a bench or sofa, feet on the floor; lift the hips until level with the knees. More range than the bridge.',
        cues: ['Chin tucked, eyes forward', 'Shins vertical at the top', 'Squeeze the glutes at the top'],
      },
    },
    easier: ['glute-bridge'],
  },
  {
    slug: 'frog-pump',
    name: 'Frog Pump',
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['GLUTES'],
    secondaryMuscles: ['ADDUCTORS'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '1-1-1-0',
    translations: {
      'pt-PT': {
        name: 'Frog pump',
        description: 'Ponte com as plantas dos pés juntas e os joelhos abertos. Isola o glúteo e funciona bem em séries longas.',
        cues: ['Plantas dos pés juntas', 'Repetições curtas e rápidas', 'Aperta o glúteo em cada subida'],
      },
      'en-US': {
        name: 'Frog pump',
        description: 'Bridge with the soles of the feet together and knees open. Isolates the glutes and works well for high reps.',
        cues: ['Soles of the feet together', 'Short, quick reps', 'Squeeze the glutes on every lift'],
      },
    },
    easier: [],
    harder: ['glute-bridge'],
  },
  {
    slug: 'bodyweight-good-morning',
    name: 'Bodyweight Good Morning',
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['HAMSTRINGS', 'GLUTES'],
    secondaryMuscles: ['LOWER_BACK', 'CORE'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Good morning',
        description: 'Mãos atrás da cabeça, joelhos ligeiramente dobrados; inclina o tronco à frente empurrando a anca para trás. Ensina a dobradiça de anca.',
        cues: ['Anca vai para trás, não para baixo', 'Costas direitas do início ao fim', 'Sente o alongamento atrás da coxa'],
      },
      'en-US': {
        name: 'Bodyweight good morning',
        description: 'Hands behind the head, knees slightly bent; hinge the torso forward by pushing the hips back. Teaches the hip hinge.',
        cues: ['Hips go back, not down', 'Flat back from start to finish', 'Feel the stretch in the hamstrings'],
      },
    },
    easier: [],
  },
  {
    slug: 'single-leg-rdl',
    name: 'Single-Leg Romanian Deadlift',
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['HAMSTRINGS', 'GLUTES'],
    secondaryMuscles: ['CORE', 'LOWER_BACK', 'CALVES'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 3.5,
    defaultTempo: '3-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Peso morto a uma perna',
        description: 'De pé numa perna, inclina o tronco à frente enquanto a outra perna sobe atrás, até ficares em T. Equilíbrio, glúteos e isquiotibiais.',
        cues: ['Anca quadrada, não deixes abrir', 'Joelho de apoio ligeiramente dobrado', 'Do calcanhar à cabeça em linha reta'],
      },
      'en-US': {
        name: 'Single-leg Romanian deadlift',
        description: 'Standing on one leg, hinge the torso forward while the other leg rises behind you into a T. Balance, glutes and hamstrings.',
        cues: ['Hips square, do not let them open', 'Slight bend in the standing knee', 'Straight line from heel to head'],
      },
    },
    easier: ['bodyweight-good-morning'],
  },
  {
    slug: 'dumbbell-single-leg-rdl',
    name: 'Dumbbell Single-Leg Romanian Deadlift',
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['HAMSTRINGS', 'GLUTES'],
    secondaryMuscles: ['CORE', 'LOWER_BACK', 'FOREARMS'],
    equipment: ['DUMBBELLS'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 3.5,
    defaultTempo: '3-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Peso morto a uma perna com haltere',
        description: 'A mesma dobradiça a uma perna, com um haltere na mão oposta à perna de apoio. Mais carga e mais trabalho de estabilidade.',
        cues: ['Haltere desce junto à perna', 'Costas direitas, olhar para o chão à frente', 'Sobe apertando o glúteo'],
      },
      'en-US': {
        name: 'Dumbbell single-leg Romanian deadlift',
        description: 'The same single-leg hinge holding a dumbbell in the hand opposite the standing leg. More load and more stability work.',
        cues: ['Dumbbell slides down close to the leg', 'Flat back, eyes on the floor ahead', 'Stand by squeezing the glute'],
      },
    },
    easier: ['single-leg-rdl'],
  },
  {
    slug: 'kettlebell-swing',
    name: 'Kettlebell Swing',
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['GLUTES', 'HAMSTRINGS'],
    secondaryMuscles: ['CORE', 'LOWER_BACK', 'SHOULDERS', 'CARDIOVASCULAR'],
    equipment: ['KETTLEBELL'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 9.8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Swing com kettlebell',
        description: 'Dobradiça explosiva: o kettlebell passa entre as pernas e sobe até à altura do peito impulsionado pela anca, não pelos braços.',
        cues: ['A anca empurra, os braços só guiam', 'Costas sempre direitas', 'Aperta os glúteos no topo do swing'],
      },
      'en-US': {
        name: 'Kettlebell swing',
        description: 'Explosive hinge: the kettlebell passes between the legs and rises to chest height driven by the hips, not the arms.',
        cues: ['Hips drive, arms only guide', 'Back always flat', 'Squeeze the glutes at the top of the swing'],
      },
    },
    easier: ['bodyweight-good-morning'],
  },
  {
    slug: 'nordic-curl-negative',
    name: 'Nordic Curl (Negative)',
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['HAMSTRINGS'],
    secondaryMuscles: ['GLUTES', 'CORE', 'CALVES'],
    equipment: ['NONE'],
    difficulty: 4,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: '5-0-0-0',
    translations: {
      'pt-PT': {
        name: 'Nordic curl (negativo)',
        description: 'De joelhos com os pés presos debaixo de um sofá, desce o tronco à frente o mais devagar possível e apara a queda com as mãos. Isquiotibiais de ferro.',
        cues: ['Anca esticada, corpo em linha dos joelhos à cabeça', 'Desce o mais devagar possível', 'Usa as mãos para amortecer no fim'],
      },
      'en-US': {
        name: 'Nordic curl (negative)',
        description: 'Kneeling with feet anchored under a sofa, lower the torso forward as slowly as possible and catch yourself with your hands. Bulletproof hamstrings.',
        cues: ['Hips extended, straight line from knees to head', 'Lower as slowly as possible', 'Use the hands to cushion the end'],
      },
    },
    easier: ['single-leg-rdl'],
  },
];
