/** Afundos e variantes unilaterais. */
import type { SeedExercise } from '../types';

export const LUNGE_EXERCISES: SeedExercise[] = [
  {
    slug: 'reverse-lunge',
    name: 'Reverse Lunge',
    category: 'STRENGTH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE', 'CALVES'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Afundo inverso',
        description: 'Dá um passo atrás e baixa o joelho de trás em direção ao chão. Mais amigo dos joelhos que o afundo à frente; boa porta de entrada.',
        cues: ['Passo largo para trás', 'Joelho da frente por cima do tornozelo', 'Tronco vertical, empurra o calcanhar da frente'],
      },
      'en-US': {
        name: 'Reverse lunge',
        description: 'Step back and lower the rear knee toward the floor. Friendlier on the knees than the forward lunge; a good entry point.',
        cues: ['Long step back', 'Front knee over the ankle', 'Torso upright, drive through the front heel'],
      },
    },
    easier: ['split-squat'],
  },
  {
    slug: 'split-squat',
    name: 'Split Squat',
    category: 'STRENGTH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Afundo estático',
        description: 'Posição de afundo fixa: sobe e desce sem mexer os pés. Ensina o padrão com o máximo de estabilidade.',
        cues: ['Pés à largura da anca, um à frente do outro', 'Desce a direito, joelho de trás quase ao chão', 'Peso no calcanhar da frente'],
      },
      'en-US': {
        name: 'Split squat',
        description: 'Fixed lunge stance: go up and down without moving the feet. Teaches the pattern with maximum stability.',
        cues: ['Feet hip-width, one in front of the other', 'Lower straight down, rear knee almost to the floor', 'Weight in the front heel'],
      },
    },
    easier: ['chair-squat'],
  },
  {
    slug: 'forward-lunge',
    name: 'Forward Lunge',
    category: 'STRENGTH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE', 'CALVES'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Afundo à frente',
        description: 'Dá um passo à frente, baixa a anca e volta à posição inicial empurrando o calcanhar. Exige mais travagem e controlo que o inverso.',
        cues: ['Passo largo, aterra com o pé inteiro', 'Joelho da frente não passa muito a ponta do pé', 'Empurra com força para voltar'],
      },
      'en-US': {
        name: 'Forward lunge',
        description: 'Step forward, lower the hips and push back to the start through the heel. Requires more braking and control than the reverse lunge.',
        cues: ['Long step, land with the whole foot', 'Front knee does not travel far past the toes', 'Push hard to return'],
      },
    },
    easier: ['reverse-lunge'],
  },
  {
    slug: 'walking-lunge',
    name: 'Walking Lunge',
    category: 'STRENGTH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE', 'CALVES'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Afundos em caminhada',
        description: 'Afundos alternados a avançar pelo espaço. Conta-se o total de passos. Ótimo para volume de pernas e coordenação.',
        cues: ['Passos longos e controlados', 'Tronco alto, olhar em frente', 'Junta o pé de trás só depois de subir'],
      },
      'en-US': {
        name: 'Walking lunge',
        description: 'Alternating lunges moving forward through space. Count total steps. Great for leg volume and coordination.',
        cues: ['Long, controlled steps', 'Tall torso, eyes forward', 'Bring the back foot through only after standing'],
      },
    },
    easier: ['forward-lunge'],
  },
  {
    slug: 'bulgarian-split-squat',
    name: 'Bulgarian Split Squat',
    category: 'STRENGTH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE', 'ADDUCTORS'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Agachamento búlgaro',
        description: 'Afundo com o pé de trás apoiado numa cadeira, sofá ou cama. Um dos melhores exercícios de pernas sem equipamento.',
        cues: ['Pé de trás só para equilibrar', 'Desce a direito, joelho de trás em direção ao chão', 'Passo longo para mais glúteo, curto para mais quadríceps'],
      },
      'en-US': {
        name: 'Bulgarian split squat',
        description: 'Lunge with the rear foot on a chair, sofa or bed. One of the best equipment-free leg exercises.',
        cues: ['Rear foot is only for balance', 'Lower straight down, rear knee toward the floor', 'Long step for more glutes, short for more quads'],
      },
    },
    easier: ['split-squat'],
  },
  {
    slug: 'jumping-lunge',
    name: 'Jumping Lunge',
    category: 'PLYOMETRIC',
    movementPattern: 'JUMP',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CALVES', 'CARDIOVASCULAR'],
    equipment: ['NONE'],
    difficulty: 4,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Afundos com salto',
        description: 'Em posição de afundo, salta e troca as pernas no ar, aterrando em afundo do outro lado. Conta o total de saltos.',
        cues: ['Aterra suave com o joelho de trás perto do chão', 'Tronco vertical, braços a ajudar', 'Ritmo constante'],
      },
      'en-US': {
        name: 'Jumping lunge',
        description: 'From a lunge, jump and switch legs in the air, landing in a lunge on the other side. Count total jumps.',
        cues: ['Land softly with the rear knee near the floor', 'Torso upright, arms assisting', 'Steady rhythm'],
      },
    },
    easier: ['walking-lunge'],
  },
  {
    slug: 'lateral-lunge',
    name: 'Lateral Lunge',
    category: 'STRENGTH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['GLUTES', 'QUADS', 'ADDUCTORS'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Afundo lateral',
        description: 'Passo largo para o lado, senta a anca para trás sobre essa perna mantendo a outra esticada. Trabalha o plano lateral, que costuma faltar.',
        cues: ['Pés apontam em frente', 'Anca para trás, peito alto', 'Perna esticada fica com o pé inteiro no chão'],
      },
      'en-US': {
        name: 'Lateral lunge',
        description: 'Big step to the side, sit the hips back over that leg keeping the other one straight. Trains the often-missing lateral plane.',
        cues: ['Toes point forward', 'Hips back, chest tall', 'Straight leg keeps the whole foot on the floor'],
      },
    },
    easier: ['bodyweight-squat'],
  },
  {
    slug: 'curtsy-lunge',
    name: 'Curtsy Lunge',
    category: 'STRENGTH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['GLUTES', 'QUADS'],
    secondaryMuscles: ['ABDUCTORS', 'ADDUCTORS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Afundo cruzado',
        description: 'Passo para trás cruzando por detrás da perna de apoio, como numa vénia. Ênfase no glúteo médio.',
        cues: ['Cruza a perna atrás e para o lado', 'Anca e ombros virados para a frente', 'Joelho da frente alinhado com o pé'],
      },
      'en-US': {
        name: 'Curtsy lunge',
        description: 'Step back crossing behind the standing leg, like a curtsy. Emphasizes the glute medius.',
        cues: ['Cross the leg back and to the side', 'Hips and shoulders face forward', 'Front knee aligned with the foot'],
      },
    },
    easier: ['reverse-lunge'],
  },
  {
    slug: 'step-up',
    name: 'Step-Up',
    category: 'STRENGTH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CALVES', 'CORE'],
    equipment: ['BENCH'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Subida ao banco',
        description: 'Sobe para um banco, caixa ou degrau alto com uma perna e desce controlado. Quanto mais alto o apoio, mais glúteo.',
        cues: ['Pé inteiro em cima do apoio', 'Sobe sem impulso da perna de trás', 'Desce devagar, controla a descida'],
      },
      'en-US': {
        name: 'Step-up',
        description: 'Step onto a bench, box or tall step with one leg and lower with control. The higher the surface, the more glutes.',
        cues: ['Whole foot on the surface', 'Step up without pushing off the back leg', 'Lower slowly, control the descent'],
      },
    },
    easier: ['reverse-lunge'],
  },
];
