/** Mobilidade e alongamentos — aquecimento e retorno à calma. Todos difficulty 1 e DURATION. */
import type { SeedExercise } from '../types';

export const MOBILITY_EXERCISES: SeedExercise[] = [
  {
    slug: 'arm-circles',
    name: 'Arm Circles',
    category: 'MOBILITY',
    movementPattern: 'ROTATION',
    primaryMuscles: ['SHOULDERS'],
    secondaryMuscles: ['UPPER_BACK', 'CHEST'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 2.8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Círculos com os braços',
        description: 'Braços esticados de lado, faz círculos pequenos que vão crescendo; metade do tempo à frente, metade para trás. Aquece os ombros.',
        cues: ['Braços esticados à altura dos ombros', 'Começa pequeno e vai aumentando', 'Troca de sentido a meio'],
      },
      'en-US': {
        name: 'Arm circles',
        description: 'Arms straight out to the sides, make small circles that grow bigger; half the time forward, half backward. Warms up the shoulders.',
        cues: ['Straight arms at shoulder height', 'Start small and grow', 'Switch direction halfway'],
      },
    },
    easier: [],
  },
  {
    slug: 'leg-swings',
    name: 'Leg Swings',
    category: 'MOBILITY',
    movementPattern: 'HINGE',
    primaryMuscles: ['HIP_FLEXORS', 'HAMSTRINGS'],
    secondaryMuscles: ['GLUTES', 'ADDUCTORS'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: true,
    metValue: 2.8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Balanços de perna',
        description: 'Apoiado numa parede, balança uma perna à frente e atrás com a perna esticada, depois de lado a lado. Solta a anca antes de agachar ou correr.',
        cues: ['Tronco direito, só a perna se mexe', 'Amplitude aumenta aos poucos', 'Faz à frente-atrás e depois lado-a-lado'],
      },
      'en-US': {
        name: 'Leg swings',
        description: 'Holding a wall, swing one straight leg forward and back, then side to side. Loosens the hips before squatting or running.',
        cues: ['Torso tall, only the leg moves', 'Range grows gradually', 'Do front-to-back then side-to-side'],
      },
    },
    easier: [],
  },
  {
    slug: 'hip-circles',
    name: 'Hip Circles',
    category: 'MOBILITY',
    movementPattern: 'ROTATION',
    primaryMuscles: ['HIP_FLEXORS', 'GLUTES'],
    secondaryMuscles: ['LOWER_BACK', 'CORE'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 2.8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Círculos com a anca',
        description: 'Mãos na cintura, desenha círculos grandes com a anca num sentido e depois no outro. Lubrifica a anca e a lombar.',
        cues: ['Círculos grandes e lentos', 'Joelhos ligeiramente dobrados', 'Troca de sentido a meio'],
      },
      'en-US': {
        name: 'Hip circles',
        description: 'Hands on hips, draw big circles with the hips one way and then the other. Lubricates the hips and lower back.',
        cues: ['Big, slow circles', 'Knees slightly bent', 'Switch direction halfway'],
      },
    },
    easier: [],
  },
  {
    slug: 'ankle-circles',
    name: 'Ankle Circles',
    category: 'MOBILITY',
    movementPattern: 'ROTATION',
    primaryMuscles: ['CALVES'],
    secondaryMuscles: [],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: true,
    metValue: 2.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Círculos com o tornozelo',
        description: 'Com o pé levantado, roda o tornozelo em círculos nos dois sentidos. Prepara os tornozelos para saltos e agachamentos.',
        cues: ['Círculos completos e lentos', 'Metade do tempo em cada sentido', 'Apoia-te se precisares de equilíbrio'],
      },
      'en-US': {
        name: 'Ankle circles',
        description: 'With the foot lifted, rotate the ankle in circles both ways. Prepares the ankles for jumps and squats.',
        cues: ['Full, slow circles', 'Half the time in each direction', 'Hold something if you need balance'],
      },
    },
    easier: [],
  },
  {
    slug: 'cat-cow',
    name: 'Cat-Cow',
    category: 'MOBILITY',
    movementPattern: 'HINGE',
    primaryMuscles: ['LOWER_BACK', 'CORE'],
    secondaryMuscles: ['UPPER_BACK'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 2.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Gato-vaca',
        description: 'De quatro, alterna entre arquear as costas para o teto (gato) e deixá-las descer com o peito aberto (vaca). Mobiliza toda a coluna.',
        cues: ['Movimento lento, vértebra a vértebra', 'Expira no gato, inspira na vaca', 'Mãos por baixo dos ombros'],
      },
      'en-US': {
        name: 'Cat-cow',
        description: 'On all fours, alternate between arching the back to the ceiling (cat) and letting it drop with an open chest (cow). Mobilizes the whole spine.',
        cues: ['Slow movement, vertebra by vertebra', 'Exhale on cat, inhale on cow', 'Hands under the shoulders'],
      },
    },
    easier: [],
  },
  {
    slug: 'thoracic-rotations',
    name: 'Thoracic Rotations',
    category: 'MOBILITY',
    movementPattern: 'ROTATION',
    primaryMuscles: ['UPPER_BACK', 'OBLIQUES'],
    secondaryMuscles: ['SHOULDERS', 'CHEST'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: true,
    metValue: 2.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Rotações torácicas',
        description: 'De quatro, mão atrás da cabeça; roda o cotovelo para o teto e volta a passar por baixo do corpo. Abre a parte alta das costas.',
        cues: ['Anca fixa, só o tronco roda', 'Segue o cotovelo com o olhar', 'Expira ao abrir'],
      },
      'en-US': {
        name: 'Thoracic rotations',
        description: 'On all fours, hand behind the head; rotate the elbow to the ceiling and thread it back under the body. Opens the upper back.',
        cues: ['Hips fixed, only the torso rotates', 'Follow the elbow with your eyes', 'Exhale as you open'],
      },
    },
    easier: [],
  },
  {
    slug: 'worlds-greatest-stretch',
    name: "World's Greatest Stretch",
    category: 'MOBILITY',
    movementPattern: 'LUNGE',
    primaryMuscles: ['HIP_FLEXORS', 'HAMSTRINGS', 'UPPER_BACK'],
    secondaryMuscles: ['GLUTES', 'ADDUCTORS', 'CHEST'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: true,
    metValue: 2.8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'O melhor alongamento do mundo',
        description: 'Afundo profundo com as mãos no chão; leva o cotovelo ao pé da frente e depois roda o braço para o teto. Anca, isquiotibiais e coluna num só movimento.',
        cues: ['Joelho de trás pode ficar no chão', 'Roda o tronco e segue a mão com o olhar', 'Respira fundo em cada posição'],
      },
      'en-US': {
        name: "World's greatest stretch",
        description: 'Deep lunge with hands on the floor; bring the elbow to the front foot, then rotate the arm to the ceiling. Hips, hamstrings and spine in one move.',
        cues: ['Back knee can rest on the floor', 'Rotate the torso and follow the hand with your eyes', 'Breathe deeply in each position'],
      },
    },
    easier: [],
  },
  {
    slug: 'inchworm',
    name: 'Inchworm',
    category: 'MOBILITY',
    movementPattern: 'LOCOMOTION',
    primaryMuscles: ['HAMSTRINGS', 'CORE'],
    secondaryMuscles: ['SHOULDERS', 'CALVES', 'CHEST'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Inchworm',
        description: 'De pé, dobra à frente, caminha com as mãos até à prancha e volta a caminhar com os pés até às mãos. Aquece isquiotibiais, ombros e core.',
        cues: ['Pernas o mais esticadas que conseguires', 'Prancha firme antes de voltar', 'Passos pequenos com os pés'],
      },
      'en-US': {
        name: 'Inchworm',
        description: 'From standing, fold forward, walk the hands out to a plank and walk the feet back to the hands. Warms up hamstrings, shoulders and core.',
        cues: ['Legs as straight as you can', 'Solid plank before walking back', 'Small steps with the feet'],
      },
    },
    easier: [],
  },
  {
    slug: 'downward-dog-to-cobra',
    name: 'Downward Dog to Cobra',
    category: 'MOBILITY',
    movementPattern: 'HINGE',
    primaryMuscles: ['HAMSTRINGS', 'LOWER_BACK', 'SHOULDERS'],
    secondaryMuscles: ['CALVES', 'CORE', 'CHEST'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 2.8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Cão a olhar para baixo e cobra',
        description: 'Alterna entre o V invertido (anca alta, calcanhares ao chão) e a cobra (anca no chão, peito aberto). Toda a cadeia posterior e a coluna.',
        cues: ['No cão, empurra o chão e estica as costas', 'Na cobra, ombros longe das orelhas', 'Passa de uma posição à outra devagar'],
      },
      'en-US': {
        name: 'Downward dog to cobra',
        description: 'Alternate between the inverted V (hips high, heels down) and cobra (hips on the floor, chest open). Whole posterior chain and spine.',
        cues: ['In the dog, push the floor and lengthen the back', 'In cobra, shoulders away from the ears', 'Move between positions slowly'],
      },
    },
    easier: [],
  },
  {
    slug: 'deep-squat-hold',
    name: 'Deep Squat Hold',
    category: 'MOBILITY',
    movementPattern: 'SQUAT',
    primaryMuscles: ['HIP_FLEXORS', 'ADDUCTORS', 'CALVES'],
    secondaryMuscles: ['GLUTES', 'LOWER_BACK'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 2.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Agachamento profundo (posição)',
        description: 'Desce ao agachamento mais fundo que conseguires e fica lá, com os cotovelos a empurrar os joelhos para fora. Mobilidade de anca e tornozelo.',
        cues: ['Calcanhares no chão; se subirem, apoia-te em algo', 'Cotovelos empurram os joelhos para fora', 'Peito alto, respira devagar'],
      },
      'en-US': {
        name: 'Deep squat hold',
        description: 'Lower into the deepest squat you can and stay there, elbows pushing the knees out. Hip and ankle mobility.',
        cues: ['Heels down; if they lift, hold onto something', 'Elbows push the knees out', 'Tall chest, breathe slowly'],
      },
    },
    easier: [],
  },
  {
    slug: 'hamstring-stretch',
    name: 'Hamstring Stretch',
    category: 'STRETCH',
    movementPattern: 'HINGE',
    primaryMuscles: ['HAMSTRINGS'],
    secondaryMuscles: ['CALVES', 'LOWER_BACK'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: true,
    metValue: 2.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Alongamento dos isquiotibiais',
        description: 'Sentado ou de pé com uma perna esticada à frente e o calcanhar apoiado, inclina o tronco à frente com as costas direitas até sentir atrás da coxa.',
        cues: ['Costas direitas, inclina a partir da anca', 'Ponta do pé para cima', 'Sem ressaltos, respira e relaxa'],
      },
      'en-US': {
        name: 'Hamstring stretch',
        description: 'Seated or standing with one leg straight in front and the heel resting, hinge the torso forward with a flat back until you feel the back of the thigh.',
        cues: ['Flat back, hinge from the hips', 'Toes pointing up', 'No bouncing, breathe and relax'],
      },
    },
    easier: [],
  },
  {
    slug: 'quad-stretch',
    name: 'Standing Quad Stretch',
    category: 'STRETCH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['QUADS', 'HIP_FLEXORS'],
    secondaryMuscles: [],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: true,
    metValue: 2.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Alongamento do quadríceps',
        description: 'De pé, agarra o pé atrás e puxa o calcanhar ao glúteo, joelhos juntos e anca à frente.',
        cues: ['Joelhos lado a lado', 'Empurra a anca à frente para sentir mais', 'Apoia-te na parede se precisares'],
      },
      'en-US': {
        name: 'Standing quad stretch',
        description: 'Standing, grab the foot behind you and pull the heel to the glute, knees together and hips forward.',
        cues: ['Knees side by side', 'Push the hips forward to feel more', 'Hold a wall if needed'],
      },
    },
    easier: [],
  },
  {
    slug: 'kneeling-hip-flexor-stretch',
    name: 'Kneeling Hip Flexor Stretch',
    category: 'STRETCH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['HIP_FLEXORS'],
    secondaryMuscles: ['QUADS', 'GLUTES'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: true,
    metValue: 2.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Alongamento dos flexores da anca',
        description: 'Em afundo com o joelho de trás no chão, aperta o glúteo e empurra a anca à frente. Essencial para quem passa o dia sentado.',
        cues: ['Aperta o glúteo da perna de trás', 'Tronco vertical, não arqueies a lombar', 'Levanta o braço do mesmo lado para intensificar'],
      },
      'en-US': {
        name: 'Kneeling hip flexor stretch',
        description: 'In a lunge with the rear knee on the floor, squeeze the glute and push the hips forward. Essential for anyone who sits all day.',
        cues: ['Squeeze the glute of the rear leg', 'Torso upright, do not arch the lower back', 'Raise the same-side arm to intensify'],
      },
    },
    easier: [],
  },
  {
    slug: 'pigeon-stretch',
    name: 'Pigeon Stretch',
    category: 'STRETCH',
    movementPattern: 'HINGE',
    primaryMuscles: ['GLUTES', 'ABDUCTORS'],
    secondaryMuscles: ['HIP_FLEXORS'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: true,
    metValue: 2.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Alongamento do pombo',
        description: 'Uma perna dobrada à frente no chão, a outra esticada atrás; inclina o tronco sobre a perna da frente. Alonga profundamente o glúteo.',
        cues: ['Anca quadrada, virada para a frente', 'Inclina o tronco devagar', 'Se doer no joelho, faz deitado (figura 4)'],
      },
      'en-US': {
        name: 'Pigeon stretch',
        description: 'One leg bent in front on the floor, the other extended behind; lean the torso over the front leg. Deep glute stretch.',
        cues: ['Hips square, facing forward', 'Lean the torso slowly', 'If the knee hurts, do it lying down (figure 4)'],
      },
    },
    easier: [],
  },
  {
    slug: 'ninety-ninety-hip-stretch',
    name: '90/90 Hip Stretch',
    category: 'STRETCH',
    movementPattern: 'ROTATION',
    primaryMuscles: ['GLUTES', 'HIP_FLEXORS'],
    secondaryMuscles: ['ABDUCTORS', 'ADDUCTORS'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: true,
    metValue: 2.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Alongamento 90/90',
        description: 'Sentado com as duas pernas dobradas a 90 graus, uma à frente e outra ao lado; inclina o tronco sobre a perna da frente. Rotação interna e externa da anca.',
        cues: ['Ambos os joelhos a 90 graus', 'Costas direitas ao inclinar', 'Troca de lado rodando os joelhos'],
      },
      'en-US': {
        name: '90/90 hip stretch',
        description: 'Seated with both legs bent at 90 degrees, one in front and one to the side; lean the torso over the front leg. Internal and external hip rotation.',
        cues: ['Both knees at 90 degrees', 'Flat back as you lean', 'Switch sides by rotating the knees'],
      },
    },
    easier: [],
  },
  {
    slug: 'calf-stretch',
    name: 'Wall Calf Stretch',
    category: 'STRETCH',
    movementPattern: 'LUNGE',
    primaryMuscles: ['CALVES'],
    secondaryMuscles: [],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: true,
    metValue: 2.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Alongamento dos gémeos',
        description: 'Mãos na parede, uma perna atrás esticada com o calcanhar no chão; inclina-te à frente até sentir o gémeo. Dobra o joelho de trás para o solear.',
        cues: ['Calcanhar de trás sempre no chão', 'Pé de trás aponta para a parede', 'Segura sem ressaltos'],
      },
      'en-US': {
        name: 'Wall calf stretch',
        description: 'Hands on the wall, one leg back and straight with the heel down; lean forward until you feel the calf. Bend the back knee to target the soleus.',
        cues: ['Back heel stays on the floor', 'Back foot points at the wall', 'Hold without bouncing'],
      },
    },
    easier: [],
  },
  {
    slug: 'childs-pose',
    name: "Child's Pose",
    category: 'STRETCH',
    movementPattern: 'ISOMETRIC',
    primaryMuscles: ['LOWER_BACK', 'LATS'],
    secondaryMuscles: ['SHOULDERS', 'GLUTES'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 2.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Posição da criança',
        description: 'De joelhos, senta nos calcanhares e estica os braços à frente com a testa no chão. Relaxa a lombar e os ombros; ótimo para terminar.',
        cues: ['Joelhos afastados para ir mais fundo', 'Estica os braços e afunda o peito', 'Respira fundo para as costas'],
      },
      'en-US': {
        name: "Child's pose",
        description: 'Kneeling, sit back on the heels and reach the arms forward with the forehead on the floor. Relaxes the lower back and shoulders; great to finish.',
        cues: ['Knees apart to go deeper', 'Reach the arms and sink the chest', 'Breathe deeply into the back'],
      },
    },
    easier: [],
  },
  {
    slug: 'chest-doorway-stretch',
    name: 'Doorway Chest Stretch',
    category: 'STRETCH',
    movementPattern: 'PUSH_HORIZONTAL',
    primaryMuscles: ['CHEST', 'SHOULDERS'],
    secondaryMuscles: ['BICEPS'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 2.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Alongamento do peito na porta',
        description: 'Antebraços nos lados da ombreira com os cotovelos à altura dos ombros; dá um passo à frente até sentir o peito abrir.',
        cues: ['Cotovelos à altura dos ombros', 'Passo pequeno à frente, sem arquear a lombar', 'Ombros para baixo e para trás'],
      },
      'en-US': {
        name: 'Doorway chest stretch',
        description: 'Forearms on the sides of a door frame with elbows at shoulder height; step forward until you feel the chest open.',
        cues: ['Elbows at shoulder height', 'Small step forward, no arching the lower back', 'Shoulders down and back'],
      },
    },
    easier: [],
  },
];
