/** Puxar — horizontal (remadas) e vertical (barra, puxada no chão). */
import type { SeedExercise } from '../types';

export const PULL_EXERCISES: SeedExercise[] = [
  {
    slug: 'inverted-row-table',
    name: 'Inverted Row (Table)',
    category: 'STRENGTH',
    movementPattern: 'PULL_HORIZONTAL',
    primaryMuscles: ['UPPER_BACK', 'LATS'],
    secondaryMuscles: ['BICEPS', 'CORE', 'FOREARMS'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: '2-0-1-1',
    translations: {
      'pt-PT': {
        name: 'Remada invertida na mesa',
        description: 'Deitado debaixo de uma mesa robusta, agarra a borda e puxa o peito até à mesa. A melhor remada sem equipamento.',
        cues: ['Corpo em linha, glúteos apertados', 'Puxa com os cotovelos para trás', 'Aperta as omoplatas no topo'],
      },
      'en-US': {
        name: 'Inverted row (table)',
        description: 'Lying under a sturdy table, grab the edge and pull your chest up to it. The best equipment-free row.',
        cues: ['Body in a line, glutes tight', 'Drive the elbows back', 'Squeeze the shoulder blades at the top'],
      },
    },
    easier: ['doorway-row'],
  },
  {
    slug: 'doorway-row',
    name: 'Doorway Row',
    category: 'STRENGTH',
    movementPattern: 'PULL_HORIZONTAL',
    primaryMuscles: ['UPPER_BACK', 'LATS'],
    secondaryMuscles: ['BICEPS', 'FOREARMS'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-0-1-1',
    translations: {
      'pt-PT': {
        name: 'Remada na ombreira da porta',
        description: 'Agarra ambos os lados da ombreira, inclina o corpo para trás com os braços esticados e puxa-te para a frente. Quanto mais inclinado, mais difícil.',
        cues: ['Braços esticados no início', 'Puxa o peito até à porta', 'Corpo rígido, não dobres a anca'],
      },
      'en-US': {
        name: 'Doorway row',
        description: 'Grab both sides of a door frame, lean back with straight arms and pull yourself forward. The more you lean, the harder it gets.',
        cues: ['Arms straight at the start', 'Pull the chest to the door', 'Body rigid, do not bend at the hips'],
      },
    },
    easier: [],
  },
  {
    slug: 'towel-row',
    name: 'Towel Row',
    category: 'STRENGTH',
    movementPattern: 'PULL_HORIZONTAL',
    primaryMuscles: ['UPPER_BACK', 'LATS'],
    secondaryMuscles: ['BICEPS', 'FOREARMS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-0-1-1',
    translations: {
      'pt-PT': {
        name: 'Remada com toalha',
        description: 'Toalha presa numa porta fechada ou à volta de um poste; inclina-te para trás e rema. A pega na toalha trabalha também o antebraço.',
        cues: ['Confirma que a toalha está bem presa', 'Cotovelos junto ao corpo', 'Aperta as costas no fim de cada repetição'],
      },
      'en-US': {
        name: 'Towel row',
        description: 'Towel anchored in a closed door or around a post; lean back and row. The towel grip also works the forearms.',
        cues: ['Make sure the towel is secured', 'Elbows close to the body', 'Squeeze the back at the end of each rep'],
      },
    },
    easier: ['doorway-row'],
  },
  {
    slug: 'band-row',
    name: 'Band Row',
    category: 'STRENGTH',
    movementPattern: 'PULL_HORIZONTAL',
    primaryMuscles: ['UPPER_BACK', 'LATS'],
    secondaryMuscles: ['BICEPS', 'FOREARMS'],
    equipment: ['RESISTANCE_BAND'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-0-1-1',
    translations: {
      'pt-PT': {
        name: 'Remada com banda',
        description: 'Sentado com a banda à volta dos pés, ou de pé com a banda presa na porta. Puxa as pegas até às costelas.',
        cues: ['Peito aberto, ombros para baixo', 'Cotovelos passam pelas costelas', 'Solta devagar, sem deixar a banda puxar'],
      },
      'en-US': {
        name: 'Band row',
        description: 'Seated with the band around your feet, or standing with the band anchored in a door. Pull the handles to your ribs.',
        cues: ['Chest open, shoulders down', 'Elbows travel past the ribs', 'Release slowly, do not let the band pull you'],
      },
    },
    easier: ['doorway-row'],
  },
  {
    slug: 'band-pull-apart',
    name: 'Band Pull-Apart',
    category: 'STRENGTH',
    movementPattern: 'PULL_HORIZONTAL',
    primaryMuscles: ['UPPER_BACK', 'SHOULDERS'],
    secondaryMuscles: [],
    equipment: ['RESISTANCE_BAND'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 2.8,
    defaultTempo: '2-1-1-0',
    translations: {
      'pt-PT': {
        name: 'Pull-apart com banda',
        description: 'Banda à frente do peito com os braços esticados; afasta as mãos até a banda tocar no peito. Excelente para postura e saúde do ombro.',
        cues: ['Braços esticados à altura dos ombros', 'Aperta as omoplatas no fim', 'Não encolhas os ombros'],
      },
      'en-US': {
        name: 'Band pull-apart',
        description: 'Band in front of the chest with straight arms; pull the hands apart until the band touches your chest. Great for posture and shoulder health.',
        cues: ['Straight arms at shoulder height', 'Squeeze the shoulder blades at the end', 'Do not shrug the shoulders'],
      },
    },
    easier: [],
  },
  {
    slug: 'superman',
    name: 'Superman',
    category: 'STRENGTH',
    movementPattern: 'HINGE',
    primaryMuscles: ['LOWER_BACK', 'GLUTES'],
    secondaryMuscles: ['UPPER_BACK', 'HAMSTRINGS'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 2.8,
    defaultTempo: '1-2-1-0',
    translations: {
      'pt-PT': {
        name: 'Superman',
        description: 'Deitado de barriga para baixo, levanta braços e pernas do chão ao mesmo tempo e segura um instante. Fortalece a lombar e os glúteos.',
        cues: ['Olhar para o chão, pescoço neutro', 'Levanta braços e pernas em simultâneo', 'Segura 2 segundos no topo'],
      },
      'en-US': {
        name: 'Superman',
        description: 'Lying face down, lift arms and legs off the floor at the same time and hold briefly. Strengthens the lower back and glutes.',
        cues: ['Look at the floor, neutral neck', 'Lift arms and legs together', 'Hold 2 seconds at the top'],
      },
    },
    easier: [],
  },
  {
    slug: 'prone-ytw',
    name: 'Prone Y-T-W',
    category: 'STRENGTH',
    movementPattern: 'PULL_HORIZONTAL',
    primaryMuscles: ['UPPER_BACK', 'SHOULDERS'],
    secondaryMuscles: ['LOWER_BACK'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 2.8,
    defaultTempo: '1-2-1-0',
    translations: {
      'pt-PT': {
        name: 'Y-T-W no chão',
        description: 'De barriga para baixo, levanta os braços em Y, depois em T e depois em W, segurando em cada posição. Ativa os músculos entre as omoplatas.',
        cues: ['Polegares apontam para o teto', 'Levanta os braços sem levantar o peito', 'Segura 2 segundos em cada letra'],
      },
      'en-US': {
        name: 'Prone Y-T-W',
        description: 'Face down, raise your arms in a Y, then T, then W, holding each position. Activates the muscles between the shoulder blades.',
        cues: ['Thumbs point to the ceiling', 'Lift the arms without lifting the chest', 'Hold 2 seconds in each letter'],
      },
    },
    easier: [],
    harder: ['band-pull-apart'],
  },
  {
    slug: 'prone-lat-pulldown',
    name: 'Prone Floor Lat Pulldown',
    category: 'STRENGTH',
    movementPattern: 'PULL_VERTICAL',
    primaryMuscles: ['LATS', 'UPPER_BACK'],
    secondaryMuscles: ['SHOULDERS'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 2.8,
    defaultTempo: '1-2-1-0',
    translations: {
      'pt-PT': {
        name: 'Puxada no chão',
        description: 'De barriga para baixo com os braços esticados à frente, levanta-os e puxa os cotovelos para baixo até junto às costelas, como numa puxada vertical. Ensina o padrão de puxar sem barra.',
        cues: ['Braços levantados do chão o tempo todo', 'Cotovelos puxam para a anca', 'Aperta as axilas no fim'],
      },
      'en-US': {
        name: 'Prone floor lat pulldown',
        description: 'Face down with arms extended overhead, lift them and pull the elbows down to the ribs, like a lat pulldown. Teaches the pulling pattern without a bar.',
        cues: ['Arms stay off the floor the whole time', 'Elbows drive toward the hips', 'Squeeze the armpits at the end'],
      },
    },
    easier: [],
  },
  {
    slug: 'dead-hang',
    name: 'Dead Hang',
    category: 'STRENGTH',
    movementPattern: 'PULL_VERTICAL',
    primaryMuscles: ['FOREARMS', 'LATS'],
    secondaryMuscles: ['SHOULDERS', 'CORE'],
    equipment: ['PULL_UP_BAR'],
    difficulty: 2,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 2.8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Suspensão na barra',
        description: 'Pendurado na barra com os braços esticados. Constrói a pega e descomprime os ombros; o primeiro passo para a elevação.',
        cues: ['Pega firme, polegar por cima ou à volta', 'Ombros ativos, ligeiramente para baixo', 'Respira com calma'],
      },
      'en-US': {
        name: 'Dead hang',
        description: 'Hanging from the bar with straight arms. Builds grip and decompresses the shoulders; the first step toward the pull-up.',
        cues: ['Firm grip, thumb over or around', 'Active shoulders, slightly pulled down', 'Breathe calmly'],
      },
    },
    easier: ['prone-lat-pulldown'],
  },
  {
    slug: 'negative-pull-up',
    name: 'Negative Pull-Up',
    category: 'STRENGTH',
    movementPattern: 'PULL_VERTICAL',
    primaryMuscles: ['LATS', 'BICEPS'],
    secondaryMuscles: ['UPPER_BACK', 'FOREARMS', 'CORE'],
    equipment: ['PULL_UP_BAR'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: '5-0-0-0',
    translations: {
      'pt-PT': {
        name: 'Elevações negativas',
        description: 'Salta ou sobe numa cadeira até ao topo da barra e desce o mais devagar que conseguires. A fase excêntrica constrói a força para a elevação completa.',
        cues: ['Começa com o queixo acima da barra', 'Desce em 3 a 5 segundos', 'Termina com os braços esticados'],
      },
      'en-US': {
        name: 'Negative pull-up',
        description: 'Jump or step up to the top of the bar and lower yourself as slowly as you can. The eccentric phase builds strength for the full pull-up.',
        cues: ['Start with the chin above the bar', 'Lower over 3 to 5 seconds', 'Finish with straight arms'],
      },
    },
    easier: ['dead-hang'],
  },
  {
    slug: 'pull-up',
    name: 'Pull-Up',
    category: 'STRENGTH',
    movementPattern: 'PULL_VERTICAL',
    primaryMuscles: ['LATS', 'BICEPS'],
    secondaryMuscles: ['UPPER_BACK', 'FOREARMS', 'CORE'],
    equipment: ['PULL_UP_BAR'],
    difficulty: 4,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Elevações',
        description: 'Pega pronada, um pouco mais larga que os ombros; puxa até o queixo passar a barra e desce controlado.',
        cues: ['Começa de braços esticados', 'Puxa os cotovelos para baixo e para trás', 'Queixo acima da barra sem balançar'],
      },
      'en-US': {
        name: 'Pull-up',
        description: 'Overhand grip, slightly wider than shoulders; pull until the chin clears the bar and lower under control.',
        cues: ['Start from straight arms', 'Drive the elbows down and back', 'Chin over the bar without swinging'],
      },
    },
    easier: ['negative-pull-up'],
  },
  {
    slug: 'chin-up',
    name: 'Chin-Up',
    category: 'STRENGTH',
    movementPattern: 'PULL_VERTICAL',
    primaryMuscles: ['LATS', 'BICEPS'],
    secondaryMuscles: ['UPPER_BACK', 'FOREARMS', 'CORE'],
    equipment: ['PULL_UP_BAR'],
    difficulty: 4,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Elevações supinadas',
        description: 'Elevações com as palmas viradas para ti. Mais participação do bíceps e, para muita gente, um pouco mais fácil que a pega pronada.',
        cues: ['Palmas viradas para a cara', 'Peito para a barra', 'Desce sempre até esticar os braços'],
      },
      'en-US': {
        name: 'Chin-up',
        description: 'Pull-ups with palms facing you. More biceps involvement and, for many people, slightly easier than the overhand grip.',
        cues: ['Palms facing you', 'Chest toward the bar', 'Always lower to straight arms'],
      },
    },
    easier: ['negative-pull-up'],
  },
];
