/** Empurrar — horizontal (flexões e variantes) e vertical (pike, parede). */
import type { SeedExercise } from '../types';

export const PUSH_EXERCISES: SeedExercise[] = [
  {
    slug: 'wall-push-up',
    name: 'Wall Push-Up',
    category: 'STRENGTH',
    movementPattern: 'PUSH_HORIZONTAL',
    primaryMuscles: ['CHEST', 'TRICEPS'],
    secondaryMuscles: ['SHOULDERS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 2.8,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Flexões na parede',
        description: 'A versão mais acessível da flexão: mãos na parede, corpo em linha, aproxima o peito da parede e volta. Ideal para quem começa do zero.',
        cues: ['Corpo em linha reta dos pés à cabeça', 'Cotovelos a 45 graus, não abertos', 'Empurra a parede até esticar os braços'],
      },
      'en-US': {
        name: 'Wall push-up',
        description: 'The most accessible push-up: hands on a wall, body in a straight line, bring your chest toward the wall and push back. Ideal for absolute beginners.',
        cues: ['Straight line from feet to head', 'Elbows at 45 degrees, not flared', 'Push until your arms are straight'],
      },
    },
    easier: [],
  },
  {
    slug: 'incline-push-up',
    name: 'Incline Push-Up',
    category: 'STRENGTH',
    movementPattern: 'PUSH_HORIZONTAL',
    primaryMuscles: ['CHEST', 'TRICEPS'],
    secondaryMuscles: ['SHOULDERS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Flexões inclinadas',
        description: 'Flexões com as mãos numa mesa, bancada ou degrau. Quanto mais alto o apoio, mais fácil. Ponte natural entre a parede e o chão.',
        cues: ['Mãos à largura dos ombros no apoio', 'Glúteos apertados, anca não cai', 'Peito toca no apoio em cada repetição'],
      },
      'en-US': {
        name: 'Incline push-up',
        description: 'Push-ups with your hands on a table, counter or step. The higher the surface, the easier. The natural bridge between the wall and the floor.',
        cues: ['Hands shoulder-width on the surface', 'Squeeze glutes, hips do not sag', 'Chest touches the surface each rep'],
      },
    },
    easier: ['wall-push-up'],
  },
  {
    slug: 'knee-push-up',
    name: 'Knee Push-Up',
    category: 'STRENGTH',
    movementPattern: 'PUSH_HORIZONTAL',
    primaryMuscles: ['CHEST', 'TRICEPS'],
    secondaryMuscles: ['SHOULDERS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Flexões de joelhos',
        description: 'Flexões no chão com os joelhos apoiados. Reduz a carga sem mudar o padrão de movimento.',
        cues: ['Linha reta dos joelhos à cabeça', 'Peito desce até quase tocar o chão', 'Não deixes a anca subir primeiro'],
      },
      'en-US': {
        name: 'Knee push-up',
        description: 'Floor push-ups with your knees down. Reduces the load without changing the movement pattern.',
        cues: ['Straight line from knees to head', 'Chest lowers until almost touching', 'Do not let the hips rise first'],
      },
    },
    easier: ['incline-push-up'],
  },
  {
    slug: 'push-up',
    name: 'Push-Up',
    category: 'STRENGTH',
    movementPattern: 'PUSH_HORIZONTAL',
    primaryMuscles: ['CHEST', 'TRICEPS'],
    secondaryMuscles: ['SHOULDERS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Flexões',
        description: 'O exercício de empurrar por excelência: peito, tríceps e ombros com o core a segurar o corpo em prancha.',
        cues: ['Mãos ligeiramente mais largas que os ombros', 'Corpo rígido como uma tábua', 'Peito ao chão, braços esticam por completo'],
      },
      'en-US': {
        name: 'Push-up',
        description: 'The classic pushing exercise: chest, triceps and shoulders with the core holding a plank.',
        cues: ['Hands slightly wider than shoulders', 'Body rigid like a board', 'Chest to the floor, arms fully extend'],
      },
    },
    easier: ['knee-push-up'],
  },
  {
    slug: 'diamond-push-up',
    name: 'Diamond Push-Up',
    category: 'STRENGTH',
    movementPattern: 'PUSH_HORIZONTAL',
    primaryMuscles: ['TRICEPS', 'CHEST'],
    secondaryMuscles: ['SHOULDERS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 4,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Flexões diamante',
        description: 'Flexões com as mãos juntas a formar um diamante sob o peito. Foco no tríceps e no peito interior.',
        cues: ['Polegares e indicadores a tocar', 'Cotovelos junto ao corpo', 'Peito desce sobre as mãos'],
      },
      'en-US': {
        name: 'Diamond push-up',
        description: 'Push-ups with hands together forming a diamond under the chest. Emphasizes triceps and inner chest.',
        cues: ['Thumbs and index fingers touching', 'Elbows close to the body', 'Chest lowers over the hands'],
      },
    },
    easier: ['push-up'],
  },
  {
    slug: 'decline-push-up',
    name: 'Decline Push-Up',
    category: 'STRENGTH',
    movementPattern: 'PUSH_HORIZONTAL',
    primaryMuscles: ['CHEST', 'SHOULDERS'],
    secondaryMuscles: ['TRICEPS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 4,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Flexões com pés elevados',
        description: 'Flexões com os pés numa cadeira, sofá ou degrau. Mais carga nos braços e no peito superior.',
        cues: ['Pés num apoio estável', 'Não deixes a anca cair', 'Cabeça neutra, olhar para o chão à frente'],
      },
      'en-US': {
        name: 'Decline push-up',
        description: 'Push-ups with your feet on a chair, sofa or step. More load on the arms and upper chest.',
        cues: ['Feet on a stable surface', 'Do not let the hips sag', 'Neutral head, look at the floor ahead'],
      },
    },
    easier: ['push-up'],
  },
  {
    slug: 'archer-push-up',
    name: 'Archer Push-Up',
    category: 'STRENGTH',
    movementPattern: 'PUSH_HORIZONTAL',
    primaryMuscles: ['CHEST', 'TRICEPS'],
    secondaryMuscles: ['SHOULDERS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 5,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 3.8,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Flexões arqueiro',
        description: 'Mãos bem afastadas; desces para um lado enquanto o outro braço estica. Passo intermédio para a flexão a um braço.',
        cues: ['Mãos muito mais largas que os ombros', 'Braço de apoio fica quase esticado', 'Alterna os lados ou faz séries por lado'],
      },
      'en-US': {
        name: 'Archer push-up',
        description: 'Hands set wide; lower toward one side while the other arm straightens. A stepping stone to the one-arm push-up.',
        cues: ['Hands much wider than shoulders', 'Support arm stays nearly straight', 'Alternate sides or do sets per side'],
      },
    },
    easier: ['decline-push-up'],
  },
  {
    slug: 'pseudo-planche-push-up',
    name: 'Pseudo Planche Push-Up',
    category: 'STRENGTH',
    movementPattern: 'PUSH_HORIZONTAL',
    primaryMuscles: ['CHEST', 'SHOULDERS'],
    secondaryMuscles: ['TRICEPS', 'CORE', 'BICEPS'],
    equipment: ['NONE'],
    difficulty: 5,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Flexões pseudo-planche',
        description: 'Flexões com as mãos junto à anca e os dedos virados para fora, inclinando os ombros à frente. Muita carga nos ombros anteriores.',
        cues: ['Mãos ao nível da anca, dedos para fora', 'Ombros à frente das mãos', 'Corpo rígido durante todo o movimento'],
      },
      'en-US': {
        name: 'Pseudo planche push-up',
        description: 'Push-ups with hands near the hips and fingers turned out, leaning the shoulders forward. Heavy load on the front delts.',
        cues: ['Hands at hip level, fingers turned out', 'Shoulders in front of the hands', 'Body rigid throughout'],
      },
    },
    easier: ['diamond-push-up'],
  },
  {
    slug: 'bench-dip',
    name: 'Bench Dip',
    category: 'STRENGTH',
    movementPattern: 'PUSH_VERTICAL',
    primaryMuscles: ['TRICEPS'],
    secondaryMuscles: ['CHEST', 'SHOULDERS'],
    equipment: ['BENCH'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Fundos no banco',
        description: 'Mãos num banco ou cadeira atrás de ti, pernas à frente; dobra os cotovelos e desce a anca. Estica as pernas para dificultar.',
        cues: ['Cotovelos apontam para trás', 'Desce até 90 graus no cotovelo', 'Ombros afastados das orelhas'],
      },
      'en-US': {
        name: 'Bench dip',
        description: 'Hands on a bench or chair behind you, legs in front; bend the elbows and lower the hips. Straighten the legs to make it harder.',
        cues: ['Elbows point backwards', 'Lower to 90 degrees at the elbow', 'Shoulders away from the ears'],
      },
    },
    easier: ['knee-push-up'],
  },
  {
    slug: 'pike-push-up',
    name: 'Pike Push-Up',
    category: 'STRENGTH',
    movementPattern: 'PUSH_VERTICAL',
    primaryMuscles: ['SHOULDERS', 'TRICEPS'],
    secondaryMuscles: ['UPPER_BACK', 'CORE'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Pike push-up',
        description: 'Anca bem alta em V invertido; dobra os cotovelos e leva a cabeça em direção ao chão. Substitui o press de ombros sem equipamento.',
        cues: ['Anca alta, pernas o mais esticadas possível', 'Cabeça desce à frente das mãos', 'Empurra o chão para longe'],
      },
      'en-US': {
        name: 'Pike push-up',
        description: 'Hips high in an inverted V; bend the elbows and lower your head toward the floor. Replaces the shoulder press with no equipment.',
        cues: ['Hips high, legs as straight as possible', 'Head lowers in front of the hands', 'Push the floor away'],
      },
    },
    easier: ['push-up'],
  },
  {
    slug: 'elevated-pike-push-up',
    name: 'Elevated Pike Push-Up',
    category: 'STRENGTH',
    movementPattern: 'PUSH_VERTICAL',
    primaryMuscles: ['SHOULDERS', 'TRICEPS'],
    secondaryMuscles: ['UPPER_BACK', 'CORE'],
    equipment: ['NONE'],
    difficulty: 4,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Pike push-up com pés elevados',
        description: 'Pike push-up com os pés numa cadeira ou sofá, tronco quase vertical. Aproxima-se do handstand push-up.',
        cues: ['Anca por cima dos ombros', 'Cabeça desce à frente das mãos', 'Core apertado para não arquear'],
      },
      'en-US': {
        name: 'Elevated pike push-up',
        description: 'Pike push-up with feet on a chair or sofa, torso nearly vertical. Gets close to the handstand push-up.',
        cues: ['Hips stacked over the shoulders', 'Head lowers in front of the hands', 'Brace the core to avoid arching'],
      },
    },
    easier: ['pike-push-up'],
  },
  {
    slug: 'wall-handstand-hold',
    name: 'Wall Handstand Hold',
    category: 'STRENGTH',
    movementPattern: 'PUSH_VERTICAL',
    primaryMuscles: ['SHOULDERS', 'TRICEPS'],
    secondaryMuscles: ['CORE', 'UPPER_BACK', 'FOREARMS'],
    equipment: ['NONE'],
    difficulty: 4,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 3.8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Pino na parede',
        description: 'Posição de pino com os pés apoiados na parede. Constrói força e estabilidade de ombro para o handstand push-up.',
        cues: ['Empurra o chão, ombros junto às orelhas', 'Glúteos e core apertados', 'Sai da posição com controlo'],
      },
      'en-US': {
        name: 'Wall handstand hold',
        description: 'Handstand with feet resting on the wall. Builds shoulder strength and stability toward the handstand push-up.',
        cues: ['Push the floor, shoulders by the ears', 'Squeeze glutes and core', 'Come down with control'],
      },
    },
    easier: ['elevated-pike-push-up'],
  },
];
