/** Agachar — parede, cadeira, agachamento e variantes até ao pistol. */
import type { SeedExercise } from '../types';

export const SQUAT_EXERCISES: SeedExercise[] = [
  {
    slug: 'wall-sit',
    name: 'Wall Sit',
    category: 'STRENGTH',
    movementPattern: 'ISOMETRIC',
    primaryMuscles: ['QUADS'],
    secondaryMuscles: ['GLUTES', 'CORE'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'DURATION',
    isUnilateral: false,
    metValue: 3.3,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Cadeira na parede',
        description: 'Costas na parede, joelhos a 90 graus, como se estivesses sentado numa cadeira invisível. Isométrico simples para os quadríceps.',
        cues: ['Costas totalmente encostadas', 'Joelhos por cima dos tornozelos', 'Peso nos calcanhares'],
      },
      'en-US': {
        name: 'Wall sit',
        description: 'Back against the wall, knees at 90 degrees, as if sitting on an invisible chair. Simple isometric for the quads.',
        cues: ['Back fully against the wall', 'Knees over the ankles', 'Weight in the heels'],
      },
    },
    easier: [],
  },
  {
    slug: 'chair-squat',
    name: 'Chair Squat',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Agachamento à cadeira',
        description: 'Senta-te numa cadeira e levanta-te sem usar as mãos. Ensina a profundidade e dá confiança a quem está a começar.',
        cues: ['Pés à largura da anca', 'Toca na cadeira de leve, não te deixes cair', 'Sobe empurrando os calcanhares'],
      },
      'en-US': {
        name: 'Chair squat',
        description: 'Sit down on a chair and stand up without using your hands. Teaches depth and builds confidence for beginners.',
        cues: ['Feet hip-width apart', 'Touch the chair lightly, do not drop', 'Stand by driving through the heels'],
      },
    },
    easier: ['wall-sit'],
  },
  {
    slug: 'bodyweight-squat',
    name: 'Bodyweight Squat',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE', 'CALVES'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Agachamento',
        description: 'O movimento base das pernas: desce a anca entre os joelhos com o peito alto e sobe. Trabalha quadríceps, glúteos e core.',
        cues: ['Pés à largura dos ombros, pontas ligeiramente para fora', 'Joelhos seguem a direção dos pés', 'Desce pelo menos até as coxas ficarem paralelas'],
      },
      'en-US': {
        name: 'Bodyweight squat',
        description: 'The foundational leg movement: lower the hips between the knees with a tall chest and stand back up. Works quads, glutes and core.',
        cues: ['Feet shoulder-width, toes slightly out', 'Knees track over the toes', 'Lower at least to parallel'],
      },
    },
    easier: ['chair-squat'],
  },
  {
    slug: 'sumo-squat',
    name: 'Sumo Squat',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['GLUTES', 'ADDUCTORS', 'QUADS'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Agachamento sumo',
        description: 'Pés bem afastados e pontas viradas para fora. Mais ênfase nos glúteos e na parte interna da coxa.',
        cues: ['Pés mais largos que os ombros, pontas a 45 graus', 'Joelhos empurram para fora', 'Tronco vertical'],
      },
      'en-US': {
        name: 'Sumo squat',
        description: 'Wide stance with toes turned out. More emphasis on glutes and inner thighs.',
        cues: ['Feet wider than shoulders, toes at 45 degrees', 'Push the knees out', 'Torso upright'],
      },
    },
    easier: ['bodyweight-squat'],
  },
  {
    slug: 'pause-squat',
    name: 'Pause Squat',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 5,
    defaultTempo: '2-3-1-0',
    translations: {
      'pt-PT': {
        name: 'Agachamento com pausa',
        description: 'Agachamento com uma pausa de 3 segundos no ponto mais baixo. Tira o impulso e obriga as pernas a fazer o trabalho.',
        cues: ['Pausa de 3 segundos em baixo', 'Mantém a tensão, não relaxes na pausa', 'Sobe com força'],
      },
      'en-US': {
        name: 'Pause squat',
        description: 'Squat with a 3-second pause at the bottom. Removes momentum and forces the legs to do the work.',
        cues: ['Pause 3 seconds at the bottom', 'Stay tight, do not relax in the pause', 'Drive up hard'],
      },
    },
    easier: ['bodyweight-squat'],
  },
  {
    slug: 'jump-squat',
    name: 'Jump Squat',
    category: 'PLYOMETRIC',
    movementPattern: 'JUMP',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['CALVES', 'HAMSTRINGS', 'CARDIOVASCULAR'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 8,
    defaultTempo: null,
    translations: {
      'pt-PT': {
        name: 'Agachamento com salto',
        description: 'Agachamento explosivo terminado num salto. Aterra suave e vai logo para a repetição seguinte.',
        cues: ['Aterra na ponta dos pés e absorve com os joelhos', 'Braços ajudam no impulso', 'Aterra em silêncio'],
      },
      'en-US': {
        name: 'Jump squat',
        description: 'Explosive squat finishing in a jump. Land softly and flow into the next rep.',
        cues: ['Land on the balls of the feet, absorb with the knees', 'Swing the arms for momentum', 'Land quietly'],
      },
    },
    easier: ['bodyweight-squat'],
  },
  {
    slug: 'assisted-pistol-squat',
    name: 'Assisted Pistol Squat',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE', 'CALVES'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 5,
    defaultTempo: '3-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Pistol assistido',
        description: 'Agachamento a uma perna segurando na ombreira da porta ou num poste para ajudar a subir. Primeiro passo para o pistol.',
        cues: ['Segura só o necessário', 'Perna livre esticada à frente', 'Calcanhar da perna de apoio sempre no chão'],
      },
      'en-US': {
        name: 'Assisted pistol squat',
        description: 'Single-leg squat holding a door frame or post to help you up. First step toward the pistol squat.',
        cues: ['Hold on only as much as needed', 'Free leg extended in front', 'Heel of the working leg stays down'],
      },
    },
    easier: ['pause-squat'],
  },
  {
    slug: 'box-pistol-squat',
    name: 'Box Pistol Squat',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE', 'CALVES'],
    equipment: ['NONE'],
    difficulty: 4,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 5,
    defaultTempo: '3-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Pistol à cadeira',
        description: 'Agachamento a uma perna até sentar numa cadeira ou caixa e levantar sem impulso. Baixa o apoio para progredir.',
        cues: ['Senta com controlo, sem cair', 'Inclina o tronco à frente para subir', 'Braços à frente para equilibrar'],
      },
      'en-US': {
        name: 'Box pistol squat',
        description: 'Single-leg squat down to a chair or box and stand up without momentum. Lower the surface to progress.',
        cues: ['Sit with control, do not drop', 'Lean the torso forward to stand', 'Arms out front for balance'],
      },
    },
    easier: ['assisted-pistol-squat'],
  },
  {
    slug: 'pistol-squat',
    name: 'Pistol Squat',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE', 'CALVES', 'HIP_FLEXORS'],
    equipment: ['NONE'],
    difficulty: 5,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 5,
    defaultTempo: '3-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Pistol',
        description: 'Agachamento completo a uma perna, com a outra esticada à frente. Exige força, equilíbrio e mobilidade de tornozelo.',
        cues: ['Desce devagar e controlado', 'Calcanhar no chão o tempo todo', 'Perna livre esticada e levantada'],
      },
      'en-US': {
        name: 'Pistol squat',
        description: 'Full single-leg squat with the other leg extended in front. Demands strength, balance and ankle mobility.',
        cues: ['Lower slowly and with control', 'Heel stays down the whole time', 'Free leg straight and lifted'],
      },
    },
    easier: ['box-pistol-squat'],
  },
  {
    slug: 'cossack-squat',
    name: 'Cossack Squat',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['QUADS', 'GLUTES', 'ADDUCTORS'],
    secondaryMuscles: ['HAMSTRINGS', 'CORE'],
    equipment: ['NONE'],
    difficulty: 3,
    metric: 'REPS',
    isUnilateral: true,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Agachamento cossaco',
        description: 'Pés muito afastados; agacha para um lado mantendo a outra perna esticada com a ponta do pé para cima. Força e mobilidade da anca ao mesmo tempo.',
        cues: ['Perna esticada com o pé virado para cima', 'Calcanhar da perna que dobra no chão', 'Peito alto, desce só até onde controlas'],
      },
      'en-US': {
        name: 'Cossack squat',
        description: 'Very wide stance; squat to one side keeping the other leg straight with toes up. Hip strength and mobility in one move.',
        cues: ['Straight leg with toes pointing up', 'Heel of the bending leg stays down', 'Tall chest, only as deep as you control'],
      },
    },
    easier: ['sumo-squat'],
  },
  {
    slug: 'goblet-squat',
    name: 'Goblet Squat',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['QUADS', 'GLUTES'],
    secondaryMuscles: ['CORE', 'UPPER_BACK', 'HAMSTRINGS'],
    equipment: ['DUMBBELLS'],
    difficulty: 2,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 5,
    defaultTempo: '2-0-1-0',
    translations: {
      'pt-PT': {
        name: 'Agachamento goblet',
        description: 'Agachamento com um haltere (ou kettlebell) seguro ao peito. A carga à frente ajuda a manter o tronco direito e a descer fundo.',
        cues: ['Haltere colado ao peito', 'Cotovelos passam por dentro dos joelhos', 'Peito alto durante toda a descida'],
      },
      'en-US': {
        name: 'Goblet squat',
        description: 'Squat holding a dumbbell (or kettlebell) at the chest. The front load helps keep the torso upright and squat deep.',
        cues: ['Weight tight against the chest', 'Elbows travel inside the knees', 'Tall chest throughout the descent'],
      },
    },
    easier: ['bodyweight-squat'],
  },
  {
    slug: 'calf-raise',
    name: 'Calf Raise',
    category: 'STRENGTH',
    movementPattern: 'SQUAT',
    primaryMuscles: ['CALVES'],
    secondaryMuscles: [],
    equipment: ['NONE'],
    difficulty: 1,
    metric: 'REPS',
    isUnilateral: false,
    metValue: 2.8,
    defaultTempo: '2-1-1-1',
    translations: {
      'pt-PT': {
        name: 'Gémeos em pé',
        description: 'Sobe na ponta dos pés e desce devagar. Num degrau, deixa o calcanhar descer abaixo do nível do degrau para maior amplitude.',
        cues: ['Sobe o mais alto possível', 'Pausa de 1 segundo no topo', 'Desce em 2 segundos'],
      },
      'en-US': {
        name: 'Calf raise',
        description: 'Rise onto the balls of your feet and lower slowly. On a step, let the heels drop below the edge for more range.',
        cues: ['Rise as high as possible', 'Pause 1 second at the top', 'Lower over 2 seconds'],
      },
    },
    easier: [],
  },
];
