/**
 * Treinos de sistema (source SYSTEM, publicados). Os nomes são a chave do upsert —
 * não os alterar sem pensar em migrar os existentes.
 *
 * Convenções:
 *  - Em exercícios unilaterais, targetReps / targetDurationSec são POR LADO.
 *  - Em blocos TABATA/EMOM/INTERVAL/AMRAP um exercício de REPS pode ter
 *    targetDurationSec (máximo de repetições no intervalo).
 *  - estimatedDurationMin e requiredEquipment são calculados em derive.ts.
 */
import type { SeedWorkout } from './types';

export const SYSTEM_WORKOUTS: SeedWorkout[] = [
  {
    name: 'Primeiro treino (15 min)',
    description:
      'Para quem está a começar do zero. Movimentos simples, sem saltos e sem chão duro: agachar, empurrar, puxar e uma prancha curta. O objetivo é acabar a sentir que foi fácil.',
    focus: 'FULL_BODY',
    difficulty: 1,
    blocks: [
      {
        type: 'WARMUP',
        format: 'CIRCUIT',
        name: 'Aquecimento',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'march-in-place', targetDurationSec: 60 },
          { slug: 'arm-circles', targetDurationSec: 30 },
          { slug: 'hip-circles', targetDurationSec: 30 },
          { slug: 'chair-squat', targetReps: 8, notes: 'Devagar, só para aquecer.' },
        ],
      },
      {
        type: 'MAIN',
        format: 'CIRCUIT',
        name: 'Circuito',
        rounds: 2,
        timeCapSec: null,
        restBetweenExercisesSec: 15,
        restBetweenRoundsSec: 60,
        notes: 'Se algum exercício for demasiado difícil, faz menos repetições e continua.',
        exercises: [
          { slug: 'chair-squat', targetReps: 10 },
          { slug: 'incline-push-up', targetReps: 8 },
          { slug: 'glute-bridge', targetReps: 10 },
          { slug: 'doorway-row', targetReps: 8 },
          { slug: 'dead-bug', targetReps: 8, notes: '8 no total, alternando os lados.' },
          { slug: 'plank', targetDurationSec: 20, notes: 'Podes apoiar os joelhos.' },
        ],
      },
      {
        type: 'COOLDOWN',
        format: 'CIRCUIT',
        name: 'Retorno à calma',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'hamstring-stretch', targetDurationSec: 20 },
          { slug: 'quad-stretch', targetDurationSec: 20 },
          { slug: 'childs-pose', targetDurationSec: 30 },
        ],
      },
    ],
  },
  {
    name: 'Corpo inteiro em casa (25 min)',
    description:
      'Circuito equilibrado de corpo inteiro sem equipamento: agachamento, flexões, afundos, remada na mesa, ponte e prancha. Três voltas a ritmo constante.',
    focus: 'FULL_BODY',
    difficulty: 2,
    blocks: [
      {
        type: 'WARMUP',
        format: 'CIRCUIT',
        name: 'Aquecimento',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'jumping-jacks', targetDurationSec: 45 },
          { slug: 'leg-swings', targetDurationSec: 20 },
          { slug: 'inchworm', targetDurationSec: 30 },
          { slug: 'bodyweight-squat', targetReps: 10 },
        ],
      },
      {
        type: 'MAIN',
        format: 'CIRCUIT',
        name: 'Circuito',
        rounds: 3,
        timeCapSec: null,
        restBetweenExercisesSec: 15,
        restBetweenRoundsSec: 60,
        exercises: [
          { slug: 'bodyweight-squat', targetReps: 15 },
          { slug: 'knee-push-up', targetReps: 10, notes: 'Se for fácil, faz flexões completas.' },
          { slug: 'reverse-lunge', targetReps: 8 },
          { slug: 'inverted-row-table', targetReps: 8, notes: 'Sem mesa robusta: remada na ombreira da porta.' },
          { slug: 'glute-bridge', targetReps: 15 },
          { slug: 'plank', targetDurationSec: 30 },
        ],
      },
      {
        type: 'COOLDOWN',
        format: 'CIRCUIT',
        name: 'Retorno à calma',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'kneeling-hip-flexor-stretch', targetDurationSec: 30 },
          { slug: 'hamstring-stretch', targetDurationSec: 30 },
          { slug: 'chest-doorway-stretch', targetDurationSec: 30 },
          { slug: 'childs-pose', targetDurationSec: 30 },
        ],
      },
    ],
  },
  {
    name: 'Pernas e glúteos (30 min)',
    description:
      'Foco em glúteos e pernas só com o peso do corpo: sumo, búlgaro, ponte a uma perna, afundo lateral, cadeira na parede e gémeos, com um finisher de frog pumps.',
    focus: 'LOWER_BODY',
    difficulty: 2,
    blocks: [
      {
        type: 'WARMUP',
        format: 'CIRCUIT',
        name: 'Aquecimento',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'march-in-place', targetDurationSec: 45 },
          { slug: 'leg-swings', targetDurationSec: 20 },
          { slug: 'hip-circles', targetDurationSec: 30 },
          { slug: 'bodyweight-squat', targetReps: 10 },
          { slug: 'glute-bridge', targetReps: 10 },
        ],
      },
      {
        type: 'MAIN',
        format: 'CIRCUIT',
        name: 'Circuito de pernas',
        rounds: 3,
        timeCapSec: null,
        restBetweenExercisesSec: 15,
        restBetweenRoundsSec: 60,
        exercises: [
          { slug: 'sumo-squat', targetReps: 15 },
          { slug: 'bulgarian-split-squat', targetReps: 8, notes: 'Pé de trás no sofá ou numa cadeira.' },
          { slug: 'single-leg-glute-bridge', targetReps: 12 },
          { slug: 'lateral-lunge', targetReps: 8 },
          { slug: 'wall-sit', targetDurationSec: 40 },
          { slug: 'calf-raise', targetReps: 12 },
        ],
      },
      {
        type: 'FINISHER',
        format: 'STRAIGHT_SETS',
        name: 'Finisher de glúteos',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [{ slug: 'frog-pump', targetReps: 25, notes: 'Ritmo rápido, aperta em cada subida.' }],
      },
      {
        type: 'COOLDOWN',
        format: 'CIRCUIT',
        name: 'Retorno à calma',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'quad-stretch', targetDurationSec: 30 },
          { slug: 'pigeon-stretch', targetDurationSec: 30 },
          { slug: 'hamstring-stretch', targetDurationSec: 30 },
        ],
      },
    ],
  },
  {
    name: 'Tronco e braços (25 min)',
    description:
      'Empurrar e puxar em supersets: flexões com remada na mesa, pike push-up com superman, fundos com puxada no chão. Termina com um finisher de prancha. Precisas de uma cadeira ou banco.',
    focus: 'UPPER_BODY',
    difficulty: 3,
    blocks: [
      {
        type: 'WARMUP',
        format: 'CIRCUIT',
        name: 'Aquecimento',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'arm-circles', targetDurationSec: 30 },
          { slug: 'cat-cow', targetDurationSec: 30 },
          { slug: 'thoracic-rotations', targetDurationSec: 20 },
          { slug: 'inchworm', targetDurationSec: 30 },
          { slug: 'incline-push-up', targetReps: 8 },
          { slug: 'prone-ytw', targetReps: 6 },
        ],
      },
      {
        type: 'MAIN',
        format: 'SUPERSET',
        name: 'Superset 1: flexões + remada',
        rounds: 3,
        timeCapSec: null,
        restBetweenExercisesSec: 10,
        restBetweenRoundsSec: 60,
        exercises: [
          { slug: 'push-up', targetReps: 10, notes: 'Se não chegares a 10, termina de joelhos.' },
          { slug: 'inverted-row-table', targetReps: 8 },
        ],
      },
      {
        type: 'MAIN',
        format: 'SUPERSET',
        name: 'Superset 2: ombros + costas',
        rounds: 3,
        timeCapSec: null,
        restBetweenExercisesSec: 10,
        restBetweenRoundsSec: 60,
        exercises: [
          { slug: 'pike-push-up', targetReps: 8 },
          { slug: 'superman', targetReps: 12 },
        ],
      },
      {
        type: 'MAIN',
        format: 'SUPERSET',
        name: 'Superset 3: tríceps + dorsais',
        rounds: 2,
        timeCapSec: null,
        restBetweenExercisesSec: 10,
        restBetweenRoundsSec: 60,
        exercises: [
          { slug: 'bench-dip', targetReps: 12, notes: 'Numa cadeira estável encostada à parede.' },
          { slug: 'prone-lat-pulldown', targetReps: 12 },
        ],
      },
      {
        type: 'FINISHER',
        format: 'CIRCUIT',
        name: 'Finisher de core',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 10,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'plank-shoulder-taps', targetReps: 20 },
          { slug: 'plank', targetDurationSec: 30 },
        ],
      },
      {
        type: 'COOLDOWN',
        format: 'CIRCUIT',
        name: 'Retorno à calma',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'chest-doorway-stretch', targetDurationSec: 30 },
          { slug: 'childs-pose', targetDurationSec: 30 },
          { slug: 'cat-cow', targetDurationSec: 30 },
        ],
      },
    ],
  },
  {
    name: 'Core (15 min)',
    description:
      'Core completo em 15 minutos: prancha, elevação de pernas, prancha lateral e bicicleta em três voltas. Sem equipamento; um tapete ajuda.',
    focus: 'CORE',
    difficulty: 2,
    blocks: [
      {
        type: 'WARMUP',
        format: 'CIRCUIT',
        name: 'Ativação',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'cat-cow', targetDurationSec: 30 },
          { slug: 'bird-dog', targetReps: 8, notes: '8 no total, alternando.' },
          { slug: 'dead-bug', targetReps: 8, notes: '8 no total, alternando.' },
          { slug: 'hip-circles', targetDurationSec: 30 },
        ],
      },
      {
        type: 'MAIN',
        format: 'CIRCUIT',
        name: 'Circuito de core',
        rounds: 3,
        timeCapSec: null,
        restBetweenExercisesSec: 10,
        restBetweenRoundsSec: 45,
        exercises: [
          { slug: 'plank', targetDurationSec: 30 },
          { slug: 'leg-raises', targetReps: 10 },
          { slug: 'side-plank', targetDurationSec: 20 },
          { slug: 'bicycle-crunch', targetReps: 16, notes: '16 no total, alternando.' },
        ],
      },
      {
        type: 'COOLDOWN',
        format: 'CIRCUIT',
        name: 'Retorno à calma',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'downward-dog-to-cobra', targetDurationSec: 30 },
          { slug: 'childs-pose', targetDurationSec: 30 },
        ],
      },
    ],
  },
  {
    name: 'Cardio sem saltos (20 min)',
    description:
      'Sobe o ritmo cardíaco sem impacto nos joelhos nem barulho para os vizinhos: polichinelos sem salto, shadow boxing, meio burpee a andar, pés rápidos, agachamento e bear crawl. Três voltas.',
    focus: 'CARDIO',
    difficulty: 2,
    blocks: [
      {
        type: 'WARMUP',
        format: 'CIRCUIT',
        name: 'Aquecimento',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'march-in-place', targetDurationSec: 60 },
          { slug: 'arm-circles', targetDurationSec: 30 },
          { slug: 'hip-circles', targetDurationSec: 30 },
          { slug: 'leg-swings', targetDurationSec: 20 },
        ],
      },
      {
        type: 'MAIN',
        format: 'INTERVAL',
        name: 'Intervalos sem impacto',
        rounds: 3,
        timeCapSec: null,
        restBetweenExercisesSec: 10,
        restBetweenRoundsSec: 45,
        notes: 'Mantém um ritmo em que ainda consegues falar frases curtas.',
        exercises: [
          { slug: 'step-jacks', targetDurationSec: 40 },
          { slug: 'shadow-boxing', targetDurationSec: 40 },
          { slug: 'half-burpee', targetReps: 8, notes: 'Anda com os pés, não saltes.' },
          { slug: 'fast-feet', targetDurationSec: 30 },
          { slug: 'bodyweight-squat', targetReps: 12 },
          { slug: 'bear-crawl', targetDurationSec: 30 },
        ],
      },
      {
        type: 'COOLDOWN',
        format: 'CIRCUIT',
        name: 'Retorno à calma',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'march-in-place', targetDurationSec: 30, notes: 'Devagar, para baixar o ritmo.' },
          { slug: 'hamstring-stretch', targetDurationSec: 20 },
          { slug: 'calf-stretch', targetDurationSec: 20 },
        ],
      },
    ],
  },
  {
    name: 'HIIT 4 blocos (20 min)',
    description:
      'Quatro tabatas de 4 minutos (20 s de esforço, 10 s de pausa), cada um com dois exercícios alternados. Intenso e com saltos; descansa 1 minuto entre blocos.',
    focus: 'CARDIO',
    difficulty: 4,
    blocks: [
      {
        type: 'WARMUP',
        format: 'CIRCUIT',
        name: 'Aquecimento',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'jumping-jacks', targetDurationSec: 45 },
          { slug: 'leg-swings', targetDurationSec: 20 },
          { slug: 'inchworm', targetDurationSec: 30 },
          { slug: 'bodyweight-squat', targetReps: 10 },
        ],
      },
      {
        type: 'MAIN',
        format: 'TABATA',
        name: 'Tabata 1',
        rounds: 4,
        timeCapSec: 240,
        restBetweenExercisesSec: 10,
        restBetweenRoundsSec: 10,
        exercises: [
          { slug: 'jumping-jacks', targetDurationSec: 20 },
          { slug: 'jump-squat', targetDurationSec: 20, notes: 'Máximo de repetições em 20 s.' },
        ],
      },
      {
        type: 'MAIN',
        format: 'TABATA',
        name: 'Tabata 2',
        rounds: 4,
        timeCapSec: 240,
        restBetweenExercisesSec: 10,
        restBetweenRoundsSec: 10,
        notes: 'Descansa 60 s antes de começar.',
        exercises: [
          { slug: 'mountain-climbers', targetDurationSec: 20 },
          { slug: 'burpee', targetDurationSec: 20, notes: 'Máximo de repetições em 20 s.' },
        ],
      },
      {
        type: 'MAIN',
        format: 'TABATA',
        name: 'Tabata 3',
        rounds: 4,
        timeCapSec: 240,
        restBetweenExercisesSec: 10,
        restBetweenRoundsSec: 10,
        notes: 'Descansa 60 s antes de começar.',
        exercises: [
          { slug: 'high-knees', targetDurationSec: 20 },
          { slug: 'skater-jumps', targetDurationSec: 20, notes: 'Máximo de repetições em 20 s.' },
        ],
      },
      {
        type: 'MAIN',
        format: 'TABATA',
        name: 'Tabata 4',
        rounds: 4,
        timeCapSec: 240,
        restBetweenExercisesSec: 10,
        restBetweenRoundsSec: 10,
        notes: 'Descansa 60 s antes de começar.',
        exercises: [
          { slug: 'plank-jacks', targetDurationSec: 20 },
          { slug: 'star-jumps', targetDurationSec: 20, notes: 'Máximo de repetições em 20 s.' },
        ],
      },
      {
        type: 'COOLDOWN',
        format: 'CIRCUIT',
        name: 'Retorno à calma',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'march-in-place', targetDurationSec: 60, notes: 'Devagar, para baixar o ritmo.' },
          { slug: 'hamstring-stretch', targetDurationSec: 20 },
          { slug: 'quad-stretch', targetDurationSec: 20 },
          { slug: 'childs-pose', targetDurationSec: 30 },
        ],
      },
    ],
  },
  {
    name: 'Mobilidade da manhã (10 min)',
    description:
      'Dez minutos para acordar as articulações: coluna, anca, tornozelos e ombros. Sem esforço, só movimento e respiração. Bom para começar o dia ou antes de qualquer treino.',
    focus: 'MOBILITY',
    difficulty: 1,
    blocks: [
      {
        type: 'WARMUP',
        format: 'CIRCUIT',
        name: 'Acordar',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'march-in-place', targetDurationSec: 45 },
          { slug: 'arm-circles', targetDurationSec: 30 },
          { slug: 'hip-circles', targetDurationSec: 30 },
        ],
      },
      {
        type: 'MAIN',
        format: 'CIRCUIT',
        name: 'Fluxo de mobilidade',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 5,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'cat-cow', targetDurationSec: 45 },
          { slug: 'thoracic-rotations', targetDurationSec: 20 },
          { slug: 'worlds-greatest-stretch', targetDurationSec: 30 },
          { slug: 'downward-dog-to-cobra', targetDurationSec: 45 },
          { slug: 'deep-squat-hold', targetDurationSec: 45 },
          { slug: 'leg-swings', targetDurationSec: 20 },
          { slug: 'ankle-circles', targetDurationSec: 15 },
        ],
      },
      {
        type: 'COOLDOWN',
        format: 'CIRCUIT',
        name: 'Respirar',
        rounds: 1,
        timeCapSec: null,
        restBetweenExercisesSec: 0,
        restBetweenRoundsSec: 0,
        exercises: [
          { slug: 'ninety-ninety-hip-stretch', targetDurationSec: 30 },
          { slug: 'childs-pose', targetDurationSec: 45 },
        ],
      },
    ],
  },
];
